BEGIN;

CREATE TABLE IF NOT EXISTS portal.agent_email_addresses (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'login'
    CHECK (kind IN ('login','business','personal','recovery','public')),
  can_sign_in BOOLEAN NOT NULL DEFAULT FALSE,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  verified_at TIMESTAMPTZ,
  source TEXT NOT NULL DEFAULT 'legacy',
  created_by_agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_email_addresses_lower
  ON portal.agent_email_addresses(lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_email_addresses_primary
  ON portal.agent_email_addresses(agent_id)
  WHERE is_primary = TRUE;
CREATE INDEX IF NOT EXISTS idx_agent_email_addresses_agent
  ON portal.agent_email_addresses(agent_id);

CREATE TABLE IF NOT EXISTS portal.agent_login_identities (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  provider_subject TEXT NOT NULL,
  email_at_link TEXT,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  verified_at TIMESTAMPTZ NOT NULL,
  last_used_at TIMESTAMPTZ,
  disabled_at TIMESTAMPTZ,
  source TEXT NOT NULL DEFAULT 'sign_in',
  created_by_agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_login_identity_provider_subject
  ON portal.agent_login_identities(provider, provider_subject);
CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_login_identity_primary
  ON portal.agent_login_identities(agent_id)
  WHERE is_primary = TRUE AND disabled_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_agent_login_identities_agent
  ON portal.agent_login_identities(agent_id);

CREATE TABLE IF NOT EXISTS portal.agent_merge_history (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_agent_id INTEGER NOT NULL UNIQUE,
  target_agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
  source_email TEXT NOT NULL,
  source_snapshot JSONB NOT NULL,
  moved_references JSONB NOT NULL DEFAULT '{}'::jsonb,
  merged_by_email TEXT,
  merged_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_merge_history_target
  ON portal.agent_merge_history(target_agent_id);

ALTER TABLE portal.agent_email_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal.agent_login_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal.agent_merge_history ENABLE ROW LEVEL SECURITY;

INSERT INTO portal.agent_email_addresses (
  agent_id, email, kind, can_sign_in, is_primary, verified_at, source
)
SELECT agents.id, lower(agents.email), 'login', TRUE, TRUE,
       COALESCE(agents.created_at, NOW()), 'legacy_backfill'
FROM portal.agents AS agents
WHERE NOT EXISTS (
  SELECT 1
  FROM portal.agent_email_addresses AS addresses
  WHERE lower(addresses.email) = lower(agents.email)
);

COMMIT;
