BEGIN;

ALTER TABLE portal.agents
  ADD COLUMN IF NOT EXISTS plan_effective_from DATE,
  ADD COLUMN IF NOT EXISTS anniversary_start DATE,
  ADD COLUMN IF NOT EXISTS affiliation_term_months INTEGER,
  ADD COLUMN IF NOT EXISTS affiliation_paid_at DATE,
  ADD COLUMN IF NOT EXISTS onboarding_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS onboarding_stage TEXT NOT NULL DEFAULT 'profile',
  ADD COLUMN IF NOT EXISTS onboarding_source TEXT NOT NULL DEFAULT 'direct',
  ADD COLUMN IF NOT EXISTS onboarding_invite_id INTEGER,
  ADD COLUMN IF NOT EXISTS agreement_status TEXT NOT NULL DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS esign_transaction_id TEXT,
  ADD COLUMN IF NOT EXISTS esign_envelope_id TEXT,
  ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'pending';

ALTER TABLE portal.commerce_orders
  ADD COLUMN IF NOT EXISTS agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_commerce_orders_agent
  ON portal.commerce_orders(agent_id, created_at DESC);
UPDATE portal.commerce_orders AS orders
SET agent_id = agents.id
FROM portal.agents AS agents
WHERE orders.agent_id IS NULL
  AND orders.customer_email IS NOT NULL
  AND lower(orders.customer_email) = lower(agents.email);

CREATE TABLE IF NOT EXISTS portal.onboarding_invitations (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  token_hash TEXT NOT NULL UNIQUE,
  email TEXT,
  source TEXT NOT NULL DEFAULT 'direct',
  team_id INTEGER REFERENCES portal.teams(id) ON DELETE SET NULL,
  sponsor_agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  plan TEXT NOT NULL DEFAULT 'solo',
  affiliation_term_months INTEGER NOT NULL DEFAULT 12,
  expires_at TIMESTAMPTZ NOT NULL,
  max_uses INTEGER NOT NULL DEFAULT 1,
  use_count INTEGER NOT NULL DEFAULT 0,
  created_by_agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_onboarding_invites_team
  ON portal.onboarding_invitations(team_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_invites_expires
  ON portal.onboarding_invitations(expires_at);

UPDATE portal.agents
SET plan = CASE plan
  WHEN 'standard' THEN 'solo'
  WHEN 'growth' THEN 'legacy_growth'
  WHEN 'elite' THEN 'solo_pro'
  ELSE COALESCE(plan, 'solo')
END;

UPDATE portal.agents
SET anniversary_start = COALESCE(anniversary_start, joined_at, created_at::date),
    plan_effective_from = COALESCE(plan_effective_from, joined_at, created_at::date),
    split_pct = CASE plan
      WHEN 'solo' THEN 85
      WHEN 'solo_pro' THEN 100
      WHEN 'team_member' THEN 90
      WHEN 'team_leader' THEN 100
      WHEN 'legacy_growth' THEN 92
      ELSE split_pct
    END;

UPDATE portal.agents AS agents
SET payment_status = 'paid'
WHERE EXISTS (
  SELECT 1 FROM portal.commerce_orders AS orders
  WHERE orders.agent_id = agents.id
    AND orders.product_key IN ('one_year_membership','two_year_membership','elite_desk_fee','growth_desk_fee')
    AND orders.status IN ('paid','active')
);

ALTER TABLE portal.agents ALTER COLUMN plan SET DEFAULT 'solo';

ALTER TABLE portal.rental_deals
  ADD COLUMN IF NOT EXISTS compensation_source TEXT NOT NULL DEFAULT 'self',
  ADD COLUMN IF NOT EXISTS client_rebate NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE portal.sale_deals
  ADD COLUMN IF NOT EXISTS compensation_source TEXT NOT NULL DEFAULT 'self',
  ADD COLUMN IF NOT EXISTS client_rebate NUMERIC(14,2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS portal.team_compensation_configs (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  team_id INTEGER NOT NULL REFERENCES portal.teams(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  effective_from DATE NOT NULL,
  default_team_split_pct INTEGER NOT NULL DEFAULT 10 CHECK (default_team_split_pct IN (10, 15, 20)),
  team_lead_split_pct INTEGER NOT NULL DEFAULT 10 CHECK (team_lead_split_pct IN (10, 15, 20, 25, 30)),
  team_cap_cents INTEGER CHECK (team_cap_cents IS NULL OR team_cap_cents IN (1000000, 1500000, 2000000, 2500000)),
  created_by_email TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_team_comp_config_version UNIQUE (team_id, version)
);
CREATE INDEX IF NOT EXISTS idx_team_comp_config_effective
  ON portal.team_compensation_configs(team_id, effective_from DESC);

INSERT INTO portal.team_compensation_configs
  (team_id, version, effective_from, default_team_split_pct, team_lead_split_pct, team_cap_cents)
SELECT id, 1, CURRENT_DATE, 10, 10, NULL
FROM portal.teams
ON CONFLICT (team_id, version) DO NOTHING;

CREATE TABLE IF NOT EXISTS portal.deal_compensation_snapshots (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  deal_type TEXT NOT NULL CHECK (deal_type IN ('rental', 'sale')),
  deal_id INTEGER NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'estimated' CHECK (status IN ('estimated', 'finalized', 'void')),
  effective_date DATE NOT NULL,
  gross_commission NUMERIC(14,2) NOT NULL,
  source_type TEXT NOT NULL DEFAULT 'self' CHECK (source_type IN ('self', 'team', 'homix_rental', 'homix_sales', 'outside')),
  source_fee NUMERIC(14,2) NOT NULL DEFAULT 0,
  outside_referral NUMERIC(14,2) NOT NULL DEFAULT 0,
  commission_base NUMERIC(14,2) NOT NULL,
  company_dollar NUMERIC(14,2) NOT NULL DEFAULT 0,
  team_allocation NUMERIC(14,2) NOT NULL DEFAULT 0,
  transaction_fee NUMERIC(14,2) NOT NULL DEFAULT 0,
  rebate_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  sponsor_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  agent_net_total NUMERIC(14,2) NOT NULL DEFAULT 0,
  homix_retained NUMERIC(14,2) NOT NULL DEFAULT 0,
  policy_version TEXT NOT NULL DEFAULT '3.1',
  configuration JSONB,
  finalized_at TIMESTAMPTZ,
  finalized_by_email TEXT,
  superseded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_deal_comp_snapshot_version UNIQUE (deal_type, deal_id, version)
);
CREATE INDEX IF NOT EXISTS idx_deal_comp_snapshot_current
  ON portal.deal_compensation_snapshots(deal_type, deal_id) WHERE superseded_at IS NULL;

CREATE TABLE IF NOT EXISTS portal.deal_compensation_allocations (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  snapshot_id INTEGER NOT NULL REFERENCES portal.deal_compensation_snapshots(id) ON DELETE CASCADE,
  agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
  share_pct NUMERIC(6,3) NOT NULL,
  plan TEXT NOT NULL,
  team_id INTEGER REFERENCES portal.teams(id) ON DELETE SET NULL,
  team_config_id INTEGER REFERENCES portal.team_compensation_configs(id) ON DELETE SET NULL,
  team_leader_agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  sponsor_agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  gross_share NUMERIC(14,2) NOT NULL,
  company_dollar NUMERIC(14,2) NOT NULL DEFAULT 0,
  company_cap_credit NUMERIC(14,2) NOT NULL DEFAULT 0,
  team_leader_allocation NUMERIC(14,2) NOT NULL DEFAULT 0,
  team_cap_credit NUMERIC(14,2) NOT NULL DEFAULT 0,
  transaction_fee NUMERIC(14,2) NOT NULL DEFAULT 0,
  rebate_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  sponsor_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  agent_net NUMERIC(14,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_deal_comp_allocation_agent UNIQUE (snapshot_id, agent_id)
);
CREATE INDEX IF NOT EXISTS idx_deal_comp_allocation_agent
  ON portal.deal_compensation_allocations(agent_id, snapshot_id);

CREATE TABLE IF NOT EXISTS portal.sponsor_plan_rewards (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_key TEXT NOT NULL UNIQUE,
  commerce_order_id INTEGER REFERENCES portal.commerce_orders(id) ON DELETE SET NULL,
  sponsor_agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
  referred_agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
  amount_cents INTEGER NOT NULL CHECK (amount_cents >= 0),
  status TEXT NOT NULL DEFAULT 'accrued' CHECK (status IN ('accrued', 'paid', 'void')),
  earned_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sponsor_plan_rewards_sponsor_earned
  ON portal.sponsor_plan_rewards(sponsor_agent_id, earned_at DESC);

COMMIT;
