BEGIN;

ALTER TABLE portal.team_compensation_configs
  DROP CONSTRAINT IF EXISTS team_compensation_configs_team_id_fkey,
  DROP CONSTRAINT IF EXISTS team_compensation_configs_team_id_teams_id_fk,
  DROP CONSTRAINT IF EXISTS team_compensation_configs_team_id_fk;
ALTER TABLE portal.team_compensation_configs
  ADD CONSTRAINT team_compensation_configs_team_id_fk
  FOREIGN KEY (team_id) REFERENCES portal.teams(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS portal.team_join_requests (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE CASCADE,
  team_id INTEGER NOT NULL,
  sponsor_agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  source_invitation_id INTEGER REFERENCES portal.onboarding_invitations(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','accepted','declined','cancelled','superseded')),
  accepted_config_id INTEGER REFERENCES portal.team_compensation_configs(id) ON DELETE SET NULL,
  decided_by_agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  decision_reason TEXT,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT team_join_requests_team_id_fk
    FOREIGN KEY (team_id) REFERENCES portal.teams(id) ON DELETE RESTRICT
);

ALTER TABLE portal.team_join_requests
  DROP CONSTRAINT IF EXISTS team_join_requests_team_id_fkey,
  DROP CONSTRAINT IF EXISTS team_join_requests_team_id_teams_id_fk,
  DROP CONSTRAINT IF EXISTS team_join_requests_team_id_fk;
ALTER TABLE portal.team_join_requests
  ADD CONSTRAINT team_join_requests_team_id_fk
  FOREIGN KEY (team_id) REFERENCES portal.teams(id) ON DELETE RESTRICT;

CREATE UNIQUE INDEX IF NOT EXISTS uq_team_join_requests_pending_agent
  ON portal.team_join_requests(agent_id)
  WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_team_join_requests_team_status
  ON portal.team_join_requests(team_id, status);
CREATE INDEX IF NOT EXISTS idx_team_join_requests_agent_created
  ON portal.team_join_requests(agent_id, created_at);

CREATE TABLE IF NOT EXISTS portal.onboarding_events (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_type TEXT NOT NULL,
  agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  actor_agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  actor_email TEXT,
  invitation_id INTEGER REFERENCES portal.onboarding_invitations(id) ON DELETE SET NULL,
  team_join_request_id INTEGER REFERENCES portal.team_join_requests(id) ON DELETE SET NULL,
  team_id INTEGER REFERENCES portal.teams(id) ON DELETE SET NULL,
  detail JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_onboarding_events_agent_created
  ON portal.onboarding_events(agent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_onboarding_events_invitation_created
  ON portal.onboarding_events(invitation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_onboarding_events_team_created
  ON portal.onboarding_events(team_id, created_at);

COMMIT;
