BEGIN;

ALTER TABLE portal.team_compensation_configs
  DROP CONSTRAINT IF EXISTS team_compensation_configs_default_team_split_pct_check,
  DROP CONSTRAINT IF EXISTS team_compensation_configs_team_lead_split_pct_check;

ALTER TABLE portal.team_compensation_configs
  ADD CONSTRAINT team_compensation_configs_default_team_split_pct_check
    CHECK (default_team_split_pct BETWEEN 0 AND 30),
  ADD CONSTRAINT team_compensation_configs_team_lead_split_pct_check
    CHECK (team_lead_split_pct BETWEEN 0 AND 40);

CREATE TABLE IF NOT EXISTS portal.compensation_obligations (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  snapshot_id INTEGER NOT NULL REFERENCES portal.deal_compensation_snapshots(id) ON DELETE CASCADE,
  allocation_id INTEGER NOT NULL REFERENCES portal.deal_compensation_allocations(id) ON DELETE CASCADE,
  recipient_agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
  source_agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
  kind TEXT NOT NULL CHECK (kind IN ('agent_net','team_split','sponsor_reward')),
  amount_cents INTEGER NOT NULL CHECK (amount_cents >= 0),
  paid_cents INTEGER NOT NULL DEFAULT 0 CHECK (paid_cents >= 0 AND paid_cents <= amount_cents),
  status TEXT NOT NULL DEFAULT 'pending_receipt',
  available_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_comp_obligation_source UNIQUE (allocation_id, kind, recipient_agent_id),
  CONSTRAINT compensation_obligations_status_check
    CHECK (status IN ('pending_receipt','payable','partially_paid','paid','void'))
);
CREATE INDEX IF NOT EXISTS idx_comp_obligation_recipient_status
  ON portal.compensation_obligations(recipient_agent_id, status);
CREATE INDEX IF NOT EXISTS idx_comp_obligation_snapshot
  ON portal.compensation_obligations(snapshot_id);

CREATE TABLE IF NOT EXISTS portal.compensation_receipts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  snapshot_id INTEGER NOT NULL UNIQUE REFERENCES portal.deal_compensation_snapshots(id) ON DELETE RESTRICT,
  amount_cents INTEGER NOT NULL CHECK (amount_cents > 0),
  received_at TIMESTAMPTZ NOT NULL,
  method TEXT NOT NULL DEFAULT 'other',
  reference TEXT,
  created_by_email TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO portal.compensation_receipts
  (snapshot_id, amount_cents, received_at, method, reference, created_by_email)
SELECT
  snapshots.id,
  round(coalesce(invoices.paid_amount, invoices.total_amount) * 100)::INTEGER,
  invoices.paid_at,
  'rental_invoice',
  invoices.invoice_number,
  'migration'
FROM portal.deal_compensation_snapshots AS snapshots
JOIN portal.invoices AS invoices
  ON snapshots.deal_type = 'rental'
 AND snapshots.deal_id = invoices.rental_deal_id
WHERE snapshots.status = 'finalized'
  AND snapshots.superseded_at IS NULL
  AND invoices.status = 'paid'
  AND invoices.paid_at IS NOT NULL
  AND coalesce(invoices.paid_amount, invoices.total_amount) > 0
ON CONFLICT (snapshot_id) DO NOTHING;

INSERT INTO portal.compensation_obligations
  (snapshot_id, allocation_id, recipient_agent_id, source_agent_id, kind,
   amount_cents, status, available_at)
SELECT
  allocations.snapshot_id,
  allocations.id,
  obligations.recipient_agent_id,
  allocations.agent_id,
  obligations.kind,
  obligations.amount_cents,
  CASE WHEN receipts.id IS NULL THEN 'pending_receipt' ELSE 'payable' END,
  receipts.received_at
FROM portal.deal_compensation_allocations AS allocations
JOIN portal.deal_compensation_snapshots AS snapshots
  ON snapshots.id = allocations.snapshot_id
LEFT JOIN portal.compensation_receipts AS receipts
  ON receipts.snapshot_id = snapshots.id
CROSS JOIN LATERAL (
  VALUES
    ('agent_net', allocations.agent_id, round(allocations.agent_net * 100)::INTEGER),
    ('team_split', allocations.team_leader_agent_id, round(allocations.team_leader_allocation * 100)::INTEGER),
    ('sponsor_reward', allocations.sponsor_agent_id, round(allocations.sponsor_amount * 100)::INTEGER)
) AS obligations(kind, recipient_agent_id, amount_cents)
WHERE snapshots.status = 'finalized'
  AND snapshots.superseded_at IS NULL
  AND obligations.recipient_agent_id IS NOT NULL
  AND obligations.amount_cents > 0
ON CONFLICT (allocation_id, kind, recipient_agent_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS portal.payout_applications (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  payout_id INTEGER NOT NULL REFERENCES portal.agent_payouts(id) ON DELETE CASCADE,
  obligation_id INTEGER NOT NULL REFERENCES portal.compensation_obligations(id) ON DELETE RESTRICT,
  amount_cents INTEGER NOT NULL CHECK (amount_cents > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_payout_application UNIQUE (payout_id, obligation_id)
);
CREATE INDEX IF NOT EXISTS idx_payout_application_obligation
  ON portal.payout_applications(obligation_id);

CREATE TABLE IF NOT EXISTS portal.anonymous_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category TEXT NOT NULL,
  message TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'zh',
  status TEXT NOT NULL DEFAULT 'new',
  admin_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT anonymous_suggestions_status_check
    CHECK (status IN ('new','reviewing','planned','closed'))
);

COMMIT;
