-- Additive Team Leader candidacy lifecycle. Existing teams remain active.

ALTER TABLE portal.teams
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';

ALTER TABLE portal.teams
  DROP CONSTRAINT IF EXISTS teams_status_check;
ALTER TABLE portal.teams
  ADD CONSTRAINT teams_status_check
  CHECK (status IN ('forming','active','inactive'));

CREATE TABLE IF NOT EXISTS portal.team_leader_applications (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  applicant_agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
  licensed_company TEXT NOT NULL,
  proposed_team_name TEXT NOT NULL,
  expected_member_count INTEGER NOT NULL CHECK (expected_member_count BETWEEN 1 AND 500),
  positioning TEXT NOT NULL,
  proposed_team_split_pct INTEGER NOT NULL CHECK (proposed_team_split_pct IN (10,15,20)),
  status TEXT NOT NULL DEFAULT 'submitted'
    CHECK (status IN ('submitted','approved','declined','withdrawn','active')),
  team_id INTEGER REFERENCES portal.teams(id) ON DELETE RESTRICT,
  team_compensation_config_id INTEGER REFERENCES portal.team_compensation_configs(id) ON DELETE RESTRICT,
  decided_by_agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
  decision_reason TEXT,
  decided_at TIMESTAMPTZ,
  agreement_status TEXT NOT NULL DEFAULT 'not_started'
    CHECK (agreement_status IN ('not_started','preparing','sent','completed','declined','voided','expired','failed')),
  esign_transaction_id TEXT,
  esign_envelope_id TEXT,
  esign_template_version_id TEXT,
  esign_evidence_package_id TEXT,
  agreement_completed_at TIMESTAMPTZ,
  activated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE portal.team_leader_applications
  ADD COLUMN IF NOT EXISTS licensed_company TEXT;
UPDATE portal.team_leader_applications AS application
SET licensed_company = agent.licensed_company
FROM portal.agents AS agent
WHERE application.applicant_agent_id = agent.id
  AND application.licensed_company IS NULL;
ALTER TABLE portal.team_leader_applications
  ALTER COLUMN licensed_company SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_team_leader_applications_open_agent
  ON portal.team_leader_applications(applicant_agent_id)
  WHERE status IN ('submitted','approved');
CREATE UNIQUE INDEX IF NOT EXISTS uq_team_leader_applications_team
  ON portal.team_leader_applications(team_id)
  WHERE team_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_team_leader_applications_status_created
  ON portal.team_leader_applications(status, created_at);
