import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { Pool } from "pg";

async function main() {
  const url = new URL(process.env.DATABASE_URL || "postgres://invalid/invalid");
  if (!["localhost", "127.0.0.1"].includes(url.hostname) || url.pathname !== "/homix_office_test") throw new Error("Only disposable local homix_office_test is allowed");
  const rootUrl = new URL(url); rootUrl.pathname = "/postgres";
  const root = new Pool({ connectionString: rootUrl.toString() });
  if (!(await root.query("SELECT 1 FROM pg_database WHERE datname='homix_office_test'")).rows.length) await root.query("CREATE DATABASE homix_office_test");
  await root.end();
  const setup = new Pool({ connectionString: url.toString() });
  await setup.query(`DROP SCHEMA IF EXISTS portal CASCADE; CREATE SCHEMA portal;
    CREATE TABLE portal.agents(id integer PRIMARY KEY,name text,email text,phone text,license_number text,licensed_company_id text,account_status text,is_admin boolean);
    CREATE TABLE portal.licensed_companies(id text PRIMARY KEY,legal_name text,is_active boolean);
    CREATE TABLE portal.settings(key text PRIMARY KEY,value text);
    INSERT INTO portal.licensed_companies VALUES('homix','Homix Realty Inc.',true);
    INSERT INTO portal.agents VALUES(1,'Office Admin','admin@example.test','2125550001',NULL,'homix','active',true),(2,'Eric Wei','eric@example.test','2125550002',NULL,'homix','active',false),(3,'Grace Xia','grace@example.test','2125550003',NULL,'homix','active',false),(4,'Inactive Agent','inactive@example.test',NULL,NULL,'homix','inactive',false);
    INSERT INTO portal.settings VALUES('content_daily_limit','1');`);
  await setup.query(await readFile("db/migrations/20260910-content-center.sql", "utf8"));
  await setup.query("ALTER TABLE portal.content_generations ADD COLUMN admin_only boolean NOT NULL DEFAULT false; ALTER TABLE portal.content_assets ADD COLUMN admin_only boolean NOT NULL DEFAULT false; ALTER TABLE portal.content_projects ADD COLUMN admin_only boolean NOT NULL DEFAULT false;");
  await setup.query(await readFile("db/migrations/20260911-content-language-pairs.sql", "utf8"));
  await setup.query(await readFile("db/migrations/20260914-office-posters.sql", "utf8"));
  await setup.query(await readFile("db/migrations/20260917-company-open-house.sql", "utf8"));
  await setup.end();
  Object.assign(process.env, { AZURE_IMAGE_ENDPOINT: "https://test.openai.azure.com/openai/v1", AZURE_IMAGE_API_KEY: "test-no-network", AZURE_IMAGE_DEPLOYMENT: "gpt-image-2", R2_ACCOUNT_ID: "test", R2_CONTENT_BUCKET_NAME: "test", R2_CONTENT_ACCESS_KEY_ID: "test", R2_CONTENT_SECRET_ACCESS_KEY: "test" });
  const { pgPool, closeDatabaseConnections } = await import("@/db");
  const routes = await import("@/app/api/content/office/route");
  const actions = await import("@/app/api/content/office/[id]/route");
  const settings = await import("@/app/api/content/settings/route");
  const assets = await import("@/app/api/content/assets/route");
  const personal = await import("@/app/api/content/generations/route");
  const { getAsset } = await import("../storage");
  const { getGeneration } = await import("../store");
  const { initialTemplates } = await import("../catalog");
  const request = (path: string, body?: unknown, origin = "http://localhost") => new Request(`http://localhost${path}`, { method: body === undefined ? "GET" : "POST", headers: { origin, "Content-Type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const ctx = (id: string) => ({ params: Promise.resolve({ id }) });
  const sql = (q: string, args: unknown[] = []) => pgPool.query(q, args).then((r) => r.rows);
  let assertions = 0;
  const equal = (actual: unknown, expected: unknown, label: string) => { assert.deepEqual(actual, expected, label); assertions++; };
  try {
    process.env.TEST_OFFICE_ACTOR = "2";
    equal((await routes.GET(request("/api/content/office"))).status, 403, "ordinary Agent cannot list office work");
    equal((await routes.POST(request("/api/content/office", {}))).status, 403, "ordinary Agent cannot create office work");
    equal((await settings.GET(request("/api/content/settings?subject=3"))).status, 403, "cannot request someone else's brand");
    equal((await assets.POST(request("/api/content/assets?subject=3", {}))).status, 403, "cannot upload as another Agent");
    process.env.TEST_OFFICE_ACTOR = "1";
    equal((await routes.POST(request("/api/content/office", {}, "https://evil.example"))).status, 403, "cross-origin request rejected");
    equal((await routes.GET(request("/api/content/office?agents=1&q=Grace"))).status, 200, "administrator searches Agents");
    const brandResponse = await settings.GET(request("/api/content/settings?subject=3"));
    equal((await brandResponse.json()).brand.name, "Grace Xia", "brand uses subject not operator");
    const templateId = randomUUID(), photo = randomUUID();
    const template = initialTemplates().find((v) => v.config.themes.includes("under_contract"))!;
    await sql("INSERT INTO portal.content_templates(id,family_id,version,status,config) VALUES($1,$1,1,'published',$2)", [templateId, JSON.stringify(template.config)]);
    await sql("INSERT INTO portal.content_assets(id,owner_agent_id,object_key,content_type,bytes,purpose,admin_only) VALUES($1,2,$2,'image/png',1,'upload',true)", [photo, `test/${photo}`]);
    const input = { kind: "listing", theme: "under_contract", language: "zh", size: "1024x1280", includePortrait: false, headline: "", message: "", additionalInstructions: "", listing: { source: "manual", address: "123 Example Street", price: "", imageAssetIds: [photo] } };
    const taskBody = { subjectAgentId: 2, request: { templateId, input, languages: ["zh", "en"] } };
    const saved = await routes.POST(request("/api/content/office", taskBody));
    equal(saved.status, 201, "save draft"); const taskId = (await saved.json()).id;
    const submitted = await actions.POST(request(`/api/content/office/${taskId}`, { action: "submit" }), ctx(taskId));
    const submission = await submitted.json();
    equal(submitted.status, 202, JSON.stringify(submission));
    const generations = await sql("SELECT * FROM portal.content_generations WHERE office_task_id=$1 ORDER BY created_at,id", [taskId]);
    equal(generations.length, 2, "two separate language outputs despite personal limit one");
    equal(generations.map((g) => g.input.language).sort(), ["en", "zh"], "single-language pair");
    equal(generations.every((g) => g.owner_agent_id === 2 && g.created_by === 1 && g.brand.name === "Eric Wei" && g.admin_only && g.review_status === "pending"), true, "ownership, audit, name and review flags");
    equal(generations.filter((g) => g.predecessor_id).length, 1, "language pair is queued in sequence");
    await actions.POST(request(`/api/content/office/${taskId}`, { action: "submit" }), ctx(taskId));
    equal((await sql("SELECT count(*) FROM portal.content_generations WHERE office_task_id=$1", [taskId]))[0].count, "2", "retry does not duplicate outputs");
    await assert.rejects(getGeneration(submission.generationId, 2), /not found/); assertions++;
    await assert.rejects(getAsset(photo, 2), /not found/); assertions++;
    equal((await actions.POST(request(`/api/content/office/${submission.generationId}`, { action: "deliver" }), ctx(submission.generationId))).status, 409, "unfinished output cannot be delivered");
    const output = randomUUID();
    await sql("INSERT INTO portal.content_assets(id,owner_agent_id,object_key,content_type,bytes,purpose,admin_only) VALUES($1,2,$2,'image/png',1,'output',true)", [output, `test/${output}`]);
    await sql("UPDATE portal.content_generations SET status='succeeded',output_asset_id=$2 WHERE id=$1", [submission.generationId, output]);
    equal((await actions.POST(request(`/api/content/office/${submission.generationId}`, { action: "deliver" }), ctx(submission.generationId))).status, 409, "unreviewed image cannot be delivered");
    equal((await actions.POST(request(`/api/content/office/${submission.generationId}`, { action: "approve" }), ctx(submission.generationId))).status, 200, "review succeeds");
    equal((await actions.POST(request(`/api/content/office/${submission.generationId}`, { action: "deliver" }), ctx(submission.generationId))).status, 200, "reviewed image delivered");
    equal((await getGeneration(submission.generationId, 2)).outputAssetId, output, "target Agent can see delivered image");
    await assert.rejects(getGeneration(submission.generationId, 3), /not found/); assertions++;
    equal((await getAsset(photo, 2)).id, photo, "target can regenerate using delivered source photos");
    const hidden = generations.find((g) => g.id !== submission.generationId)!;
    await assert.rejects(getGeneration(hidden.id, 2), /not found/); assertions++;
    equal((await actions.POST(request(`/api/content/office/${hidden.id}`, { action: "cancel" }), ctx(hidden.id))).status, 200, "unstarted queued language may be cancelled");
    equal((await sql("SELECT error FROM portal.content_generations WHERE id=$1", [hidden.id]))[0].error, "CANCELLED_BY_USER", "cancelled state recorded");
    // Delivered office work must not use the Agent's personal allowance.
    process.env.TEST_OFFICE_ACTOR = "2";
    const personalResponse = await personal.POST(request("/api/content/generations", { templateId, input, languages: ["zh"], idempotencyKey: randomUUID(), subjectAgentId: 3 }));
    equal(personalResponse.status, 202, "office generation does not consume personal allowance");
    const personalId = (await personalResponse.json()).generationId;
    equal((await getGeneration(personalId, 2)).ownerAgentId, 2, "client cannot redirect personal generation by passing subject id");
    process.env.TEST_OFFICE_ACTOR = "1";
    const secondTask = (await (await routes.POST(request("/api/content/office", taskBody))).json()).id;
    equal((await actions.POST(request(`/api/content/office/${secondTask}`, { action: "submit" }), ctx(secondTask))).status, 202, "another office task bypasses exhausted personal allowance");
    const draft = (await (await routes.POST(request("/api/content/office", taskBody))).json()).id;
    equal((await actions.DELETE(request(`/api/content/office/${draft}`), ctx(draft))).status, 200, "unused draft can be deleted");
    equal((await actions.DELETE(request(`/api/content/office/${taskId}`), ctx(taskId))).status, 409, "submitted task history is retained");
    // Company Open House preparation: identity, concurrency and prompt boundaries.
    const { enqueueOpenHouses, openHouseJobs } = await import("../open-house-jobs");
    const { prepareOpenHouseJob } = await import("../open-house-step");
    const openHouseRoutes = await import("@/app/api/content/office/open-houses/route");
    const ohTemplateId = randomUUID();
    const ohTemplate = { id: ohTemplateId, familyId: ohTemplateId, version: 1, status: "published" as const, createdAt: "", config: initialTemplates().find((v) => v.config.themes.includes("open_house"))!.config };
    await sql("INSERT INTO portal.content_templates(id,family_id,version,status,config) VALUES($1,$1,1,'published',$2)", [ohTemplateId, JSON.stringify(ohTemplate.config)]);
    const ohListing = { id: "OH1", slug: "oh1", mlsNumber: "123", status: "Active", address: { full: "100 Company Open House Lane" }, listPrice: 900000, askingPrice: 900000, beds: 3, baths: 2, sqft: 1400, annualPropertyTax: "$8,123", description: "Sunny kitchen, private patio, renovated baths, garage, and garden.", photos: [{ url: "https://example.test/house.jpg" }], openHouses: [{ id: "sat", startsAt: "2099-09-19T17:00:00Z", endsAt: "2099-09-19T19:00:00Z" }] };
    const candidate = { key: "a".repeat(64), listing: ohListing, agent: { id: 3, name: "Grace Xia", mlsId: "MLS3", photoUrl: "https://example.test/portrait.png", companyReady: true }, events: [{ date: "2099-09-19", start: "13:00", end: "15:00", timezone: "America/New_York" }], problem: null };
    Object.assign(globalThis, { __openHouseCatalog: { items: [candidate], template: ohTemplate } });
    process.env.TEST_OFFICE_ACTOR = "2";
    equal((await openHouseRoutes.GET(request("/api/content/office/open-houses"))).status, 403, "personal users cannot list company jobs");
    equal((await openHouseRoutes.POST(request("/api/content/office/open-houses", { keys: [candidate.key] }))).status, 403, "personal users cannot enqueue company posters");
    process.env.TEST_OFFICE_ACTOR = "1";
    equal((await openHouseRoutes.POST(request("/api/content/office/open-houses", { keys: [candidate.key] }, "https://evil.example"))).status, 403, "company batch rejects cross-origin writes");
    const duplicates = await Promise.all([enqueueOpenHouses(1, [candidate], ohTemplate), enqueueOpenHouses(1, [candidate], ohTemplate)]);
    equal(duplicates.flat().length, 1, "two administrators enqueue only one durable job per fingerprint");
    const ohId = duplicates.flat()[0];
    const ohJob = (await sql("SELECT * FROM portal.content_open_house_jobs WHERE id=$1", [ohId]))[0];
    equal(ohJob.subject_agent_id, 3, "matched listing agent owns the poster, not the administrator");
    equal(ohJob.request.input.listing.highlightsMode, "image_model", "automatic mode persists without fake manual review");
    equal(ohJob.request.input.listing.highlightsReviewed, undefined, "not falsely marked as human reviewed");
    equal(ohJob.request.input.events[0].start, "13:00", "source schedule retained");
    const changedResponse = await openHouseRoutes.POST(request("/api/content/office/open-houses", { keys: ["b".repeat(64)], subjectAgentId: 2, description: "invent facts" }));
    equal((await changedResponse.json()).added, 0, "changed or forged catalog keys cannot create jobs");
    // Install a prepared photo/task fixture; no storage/provider network calls.
    await sql("INSERT INTO portal.content_assets(id,owner_agent_id,object_key,content_type,bytes,purpose,admin_only) VALUES($1,3,$2,'image/png',1,'upload',true)", [ohId, `test/${ohId}`]);
    await sql("INSERT INTO portal.content_office_tasks(id,created_by,subject_agent_id,request,submission_key) VALUES($1,1,3,$2,$1)", [ohId, JSON.stringify(ohJob.request)]);
    process.env.TEST_OFFICE_ACTOR = "3";
    equal((await personal.POST(request("/api/content/generations", { ...ohJob.request, idempotencyKey: randomUUID() }))).status, 403, "personal API cannot bypass highlight review by sending image_model");
    process.env.TEST_OFFICE_ACTOR = "1";
    await Promise.all([prepareOpenHouseJob(ohId), prepareOpenHouseJob(ohId)]);
    const ohOutputs = await sql("SELECT * FROM portal.content_generations WHERE office_task_id=$1", [ohId]);
    equal(ohOutputs.length, 1, "duplicate workflow delivery creates exactly one paid image job");
    equal(ohOutputs[0].owner_agent_id, 3, "output belongs to matched agent");
    equal(ohOutputs[0].input.language, "zh", "one-click defaults to one Chinese poster");
    equal(ohOutputs[0].prompt.includes("up to FIVE"), true, "image prompt extracts up to five factual points");
    equal(ohOutputs[0].prompt.includes("$8,123"), true, "real tax passed to model");
    equal(ohOutputs[0].prompt.includes(ohListing.description), true, "full MLS remarks passed to image model");
    equal((await openHouseJobs([candidate.key]))[0].generationId, ohOutputs[0].id, "preparation status joins real generation progress");
    const blockedCandidate = { ...candidate, key: "c".repeat(64) };
    const [blockedId] = await enqueueOpenHouses(1, [blockedCandidate], ohTemplate);
    await sql("UPDATE portal.agents SET is_admin=false WHERE id=1");
    await prepareOpenHouseJob(blockedId);
    equal((await sql("SELECT status FROM portal.content_open_house_jobs WHERE id=$1", [blockedId]))[0].status, "failed", "revoked admin cannot prepare a queued poster");
    equal((await sql("SELECT count(*) FROM portal.content_office_tasks WHERE id=$1", [blockedId]))[0].count, "0", "revoked admin creates no task or image");
    await sql("UPDATE portal.agents SET is_admin=true WHERE id=1");
    console.log(`Office integration: ${assertions} assertions passed; no paid model or external messaging calls.`);
  } finally { await closeDatabaseConnections(); }
}
main().catch((e) => { console.error(e); process.exitCode = 1; });
