import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { Pool } from "pg";

async function main() {
  const url = new URL(process.env.DATABASE_URL || "postgres://invalid/invalid");
  if (!["localhost", "127.0.0.1"].includes(url.hostname) || url.pathname !== "/homix_office_test") throw new Error("Only disposable local homix_office_test is allowed");
  const rootUrl = new URL(url); rootUrl.pathname = "/postgres";
  const root = new Pool({ connectionString: rootUrl.toString() });
  if (!(await root.query("SELECT 1 FROM pg_database WHERE datname='homix_office_test'")).rows.length) await root.query("CREATE DATABASE homix_office_test");
  await root.end();
  const setup = new Pool({ connectionString: url.toString() });
  await setup.query(`DROP SCHEMA IF EXISTS portal CASCADE; CREATE SCHEMA portal;
    CREATE TABLE portal.agents(id integer PRIMARY KEY,name text,email text,phone text,license_number text,licensed_company_id text,account_status text,is_admin boolean);
    CREATE TABLE portal.licensed_companies(id text PRIMARY KEY,legal_name text,is_active boolean);
    CREATE TABLE portal.settings(key text PRIMARY KEY,value text);
    INSERT INTO portal.licensed_companies VALUES('homix','Homix Realty Inc.',true);
    INSERT INTO portal.agents VALUES(1,'Office Admin','admin@example.test','2125550001',NULL,'homix','active',true),(2,'Eric Wei','eric@example.test','2125550002',NULL,'homix','active',false),(3,'Grace Xia','grace@example.test','2125550003',NULL,'homix','active',false),(4,'Inactive Agent','inactive@example.test',NULL,NULL,'homix','inactive',false);
    INSERT INTO portal.settings VALUES('content_daily_limit','1');`);
  await setup.query(await readFile("db/migrations/20260910-content-center.sql", "utf8"));
  await setup.query("ALTER TABLE portal.content_generations ADD COLUMN admin_only boolean NOT NULL DEFAULT false; ALTER TABLE portal.content_assets ADD COLUMN admin_only boolean NOT NULL DEFAULT false; ALTER TABLE portal.content_projects ADD COLUMN admin_only boolean NOT NULL DEFAULT false;");
  await setup.query(await readFile("db/migrations/20260911-content-language-pairs.sql", "utf8"));
  await setup.query(await readFile("db/migrations/20260914-office-posters.sql", "utf8"));
  await setup.end();
  Object.assign(process.env, { AZURE_IMAGE_ENDPOINT: "https://test.openai.azure.com/openai/v1", AZURE_IMAGE_API_KEY: "test-no-network", AZURE_IMAGE_DEPLOYMENT: "gpt-image-2", R2_ACCOUNT_ID: "test", R2_CONTENT_BUCKET_NAME: "test", R2_CONTENT_ACCESS_KEY_ID: "test", R2_CONTENT_SECRET_ACCESS_KEY: "test" });
  const { pgPool, closeDatabaseConnections } = await import("@/db");
  const routes = await import("@/app/api/content/office/route");
  const actions = await import("@/app/api/content/office/[id]/route");
  const settings = await import("@/app/api/content/settings/route");
  const assets = await import("@/app/api/content/assets/route");
  const personal = await import("@/app/api/content/generations/route");
  const { getAsset } = await import("../storage");
  const { getGeneration } = await import("../store");
  const { initialTemplates } = await import("../catalog");
  const request = (path: string, body?: unknown, origin = "http://localhost") => new Request(`http://localhost${path}`, { method: body === undefined ? "GET" : "POST", headers: { origin, "Content-Type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const ctx = (id: string) => ({ params: Promise.resolve({ id }) });
  const sql = (q: string, args: unknown[] = []) => pgPool.query(q, args).then((r) => r.rows);
  let assertions = 0;
  const equal = (actual: unknown, expected: unknown, label: string) => { assert.deepEqual(actual, expected, label); assertions++; };
  try {
    process.env.TEST_OFFICE_ACTOR = "2";
    equal((await routes.GET(request("/api/content/office"))).status, 403, "ordinary Agent cannot list office work");
    equal((await routes.POST(request("/api/content/office", {}))).status, 403, "ordinary Agent cannot create office work");
    equal((await settings.GET(request("/api/content/settings?subject=3"))).status, 403, "cannot request someone else's brand");
    equal((await assets.POST(request("/api/content/assets?subject=3", {}))).status, 403, "cannot upload as another Agent");
    process.env.TEST_OFFICE_ACTOR = "1";
    equal((await routes.POST(request("/api/content/office", {}, "https://evil.example"))).status, 403, "cross-origin request rejected");
    equal((await routes.GET(request("/api/content/office?agents=1&q=Grace"))).status, 200, "administrator searches Agents");
    const brandResponse = await settings.GET(request("/api/content/settings?subject=3"));
    equal((await brandResponse.json()).brand.name, "Grace Xia", "brand uses subject not operator");
    const templateId = randomUUID(), photo = randomUUID();
    const template = initialTemplates().find((v) => v.config.themes.includes("under_contract"))!;
    await sql("INSERT INTO portal.content_templates(id,family_id,version,status,config) VALUES($1,$1,1,'published',$2)", [templateId, JSON.stringify(template.config)]);
    await sql("INSERT INTO portal.content_assets(id,owner_agent_id,object_key,content_type,bytes,purpose,admin_only) VALUES($1,2,$2,'image/png',1,'upload',true)", [photo, `test/${photo}`]);
    const input = { kind: "listing", theme: "under_contract", language: "zh", size: "1024x1280", includePortrait: false, headline: "", message: "", additionalInstructions: "", listing: { source: "manual", address: "123 Example Street", price: "", imageAssetIds: [photo] } };
    const taskBody = { subjectAgentId: 2, request: { templateId, input, languages: ["zh", "en"] } };
    const saved = await routes.POST(request("/api/content/office", taskBody));
    equal(saved.status, 201, "save draft"); const taskId = (await saved.json()).id;
    const submitted = await actions.POST(request(`/api/content/office/${taskId}`, { action: "submit" }), ctx(taskId));
    const submission = await submitted.json();
    equal(submitted.status, 202, JSON.stringify(submission));
    const generations = await sql("SELECT * FROM portal.content_generations WHERE office_task_id=$1 ORDER BY created_at,id", [taskId]);
    equal(generations.length, 2, "two separate language outputs despite personal limit one");
    equal(generations.map((g) => g.input.language).sort(), ["en", "zh"], "single-language pair");
    equal(generations.every((g) => g.owner_agent_id === 2 && g.created_by === 1 && g.brand.name === "Eric Wei" && g.admin_only && g.review_status === "pending"), true, "ownership, audit, name and review flags");
    equal(generations.filter((g) => g.predecessor_id).length, 1, "language pair is queued in sequence");
    await actions.POST(request(`/api/content/office/${taskId}`, { action: "submit" }), ctx(taskId));
    equal((await sql("SELECT count(*) FROM portal.content_generations WHERE office_task_id=$1", [taskId]))[0].count, "2", "retry does not duplicate outputs");
    await assert.rejects(getGeneration(submission.generationId, 2), /not found/); assertions++;
    await assert.rejects(getAsset(photo, 2), /not found/); assertions++;
    equal((await actions.POST(request(`/api/content/office/${submission.generationId}`, { action: "deliver" }), ctx(submission.generationId))).status, 409, "unfinished output cannot be delivered");
    const output = randomUUID();
    await sql("INSERT INTO portal.content_assets(id,owner_agent_id,object_key,content_type,bytes,purpose,admin_only) VALUES($1,2,$2,'image/png',1,'output',true)", [output, `test/${output}`]);
    await sql("UPDATE portal.content_generations SET status='succeeded',output_asset_id=$2 WHERE id=$1", [submission.generationId, output]);
    equal((await actions.POST(request(`/api/content/office/${submission.generationId}`, { action: "deliver" }), ctx(submission.generationId))).status, 409, "unreviewed image cannot be delivered");
    equal((await actions.POST(request(`/api/content/office/${submission.generationId}`, { action: "approve" }), ctx(submission.generationId))).status, 200, "review succeeds");
    equal((await actions.POST(request(`/api/content/office/${submission.generationId}`, { action: "deliver" }), ctx(submission.generationId))).status, 200, "reviewed image delivered");
    equal((await getGeneration(submission.generationId, 2)).outputAssetId, output, "target Agent can see delivered image");
    await assert.rejects(getGeneration(submission.generationId, 3), /not found/); assertions++;
    equal((await getAsset(photo, 2)).id, photo, "target can regenerate using delivered source photos");
    const hidden = generations.find((g) => g.id !== submission.generationId)!;
    await assert.rejects(getGeneration(hidden.id, 2), /not found/); assertions++;
    equal((await actions.POST(request(`/api/content/office/${hidden.id}`, { action: "cancel" }), ctx(hidden.id))).status, 200, "unstarted queued language may be cancelled");
    equal((await sql("SELECT error FROM portal.content_generations WHERE id=$1", [hidden.id]))[0].error, "CANCELLED_BY_USER", "cancelled state recorded");
    // Delivered office work must not use the Agent's personal allowance.
    process.env.TEST_OFFICE_ACTOR = "2";
    const personalResponse = await personal.POST(request("/api/content/generations", { templateId, input, languages: ["zh"], idempotencyKey: randomUUID(), subjectAgentId: 3 }));
    equal(personalResponse.status, 202, "office generation does not consume personal allowance");
    const personalId = (await personalResponse.json()).generationId;
    equal((await getGeneration(personalId, 2)).ownerAgentId, 2, "client cannot redirect personal generation by passing subject id");
    process.env.TEST_OFFICE_ACTOR = "1";
    const secondTask = (await (await routes.POST(request("/api/content/office", taskBody))).json()).id;
    equal((await actions.POST(request(`/api/content/office/${secondTask}`, { action: "submit" }), ctx(secondTask))).status, 202, "another office task bypasses exhausted personal allowance");
    const draft = (await (await routes.POST(request("/api/content/office", taskBody))).json()).id;
    equal((await actions.DELETE(request(`/api/content/office/${draft}`), ctx(draft))).status, 200, "unused draft can be deleted");
    equal((await actions.DELETE(request(`/api/content/office/${taskId}`), ctx(taskId))).status, 409, "submitted task history is retained");
    console.log(`Office integration: ${assertions} assertions passed; no paid model or external messaging calls.`);
  } finally { await closeDatabaseConnections(); }
}
main().catch((e) => { console.error(e); process.exitCode = 1; });
