import type { Sql } from "postgres";

// Idempotent Postgres schema for the portal. Runs at boot via
// instrumentation.ts (and on demand via /api/admin/ensure-schema). All
// portal tables live in the "portal" schema — public.* belongs to the
// marketing site (agents roster, inquiries) and is never touched here.
//
// Unlike the old SQLite version, this carries no legacy rename/backfill
// migrations: the Postgres database was born at the Turso cutover with the
// schema already at its current shape (data arrived via the import script).
// Future column additions follow the ADD COLUMN IF NOT EXISTS pattern at the
// bottom, paired with a marker bump in src/instrumentation.ts.
export async function ensureSchema(sql: Sql) {
  const run = (ddl: string) => sql.unsafe(ddl);

  await run(`CREATE SCHEMA IF NOT EXISTS portal`);

  console.log("Ensuring portal tables...");

  await run(`
    CREATE TABLE IF NOT EXISTS portal.buildings (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      region TEXT NOT NULL,
      name TEXT NOT NULL,
      management_company TEXT,
      submission_type TEXT NOT NULL DEFAULT 'email',
      submission_notes TEXT,
      invoice_number_format TEXT,
      bill_to_company TEXT,
      bill_to_address TEXT,
      contact_email TEXT,
      special_notes TEXT,
      is_out_of_state BOOLEAN DEFAULT FALSE,
      created_at TEXT,
      updated_at TEXT
    )`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    )`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.teams (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT NOT NULL,
      leader_agent_id INTEGER,
      notes TEXT
    )`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.agents (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      phone TEXT,
      license_number TEXT,
      license_expires_at TEXT,
      licensed_company TEXT,
      split_pct DOUBLE PRECISION NOT NULL DEFAULT 80,
      team_id INTEGER REFERENCES portal.teams(id) ON DELETE SET NULL,
      is_admin BOOLEAN NOT NULL DEFAULT FALSE,
      is_active BOOLEAN NOT NULL DEFAULT FALSE,
      approval_status TEXT NOT NULL DEFAULT 'pending',
      joined_at TEXT,
      notes TEXT,
      created_at TEXT,
      updated_at TEXT
    )`);

  // teams.leader_agent_id → agents.id (added after both tables exist to break
  // the circular reference)
  await run(`
    DO $$ BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'teams_leader_agent_fk'
      ) THEN
        ALTER TABLE portal.teams
          ADD CONSTRAINT teams_leader_agent_fk
          FOREIGN KEY (leader_agent_id) REFERENCES portal.agents(id);
      END IF;
    END $$`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.rental_deals (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      building_id INTEGER NOT NULL REFERENCES portal.buildings(id),
      unit TEXT NOT NULL,
      tenant_name TEXT NOT NULL,
      tenant_email TEXT,
      tenant_phone TEXT,
      apartment_address TEXT,
      move_in_date TEXT,
      lease_start_date TEXT,
      lease_end_date TEXT,
      rent_amount DOUBLE PRECISION,
      lease_length_months INTEGER,
      total_commission DOUBLE PRECISION NOT NULL,
      licensed_company TEXT NOT NULL,
      referrer_name TEXT,
      referrer_type TEXT,
      referrer_amount DOUBLE PRECISION,
      referrer_payment_info TEXT,
      status TEXT NOT NULL DEFAULT 'active',
      deal_date TEXT,
      source TEXT,
      notes TEXT,
      renewal_status TEXT,
      renewal_noted_at TEXT,
      renewed_to_rental_deal_id INTEGER REFERENCES portal.rental_deals(id) ON DELETE SET NULL,
      created_by_email TEXT,
      created_at TEXT,
      updated_at TEXT
    )`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.rental_deal_agents (
      rental_deal_id INTEGER NOT NULL REFERENCES portal.rental_deals(id) ON DELETE CASCADE,
      agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
      share_pct DOUBLE PRECISION NOT NULL,
      is_primary BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT,
      PRIMARY KEY (rental_deal_id, agent_id)
    )`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_rental_deal_agents_agent
      ON portal.rental_deal_agents(agent_id)`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.sale_deals (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      representation_type TEXT NOT NULL,
      stage TEXT NOT NULL DEFAULT 'pre_contract',
      status TEXT NOT NULL DEFAULT 'active',
      property_address TEXT NOT NULL,
      city TEXT,
      state TEXT,
      zip TEXT,
      property_type TEXT,
      mls_number TEXT,
      file_id TEXT,
      buyer_names TEXT,
      seller_names TEXT,
      contract_date TEXT,
      closing_date TEXT,
      purchase_price DOUBLE PRECISION,
      gross_commission DOUBLE PRECISION NOT NULL DEFAULT 0,
      referral_amount DOUBLE PRECISION,
      brokerage_fee DOUBLE PRECISION,
      listing_agent_name TEXT,
      listing_agent_email TEXT,
      listing_brokerage TEXT,
      cooperating_agent_name TEXT,
      cooperating_agent_email TEXT,
      cooperating_brokerage TEXT,
      buyer_attorney TEXT,
      seller_attorney TEXT,
      title_company TEXT,
      lender_name TEXT,
      escrow_holder TEXT,
      source TEXT,
      notes TEXT,
      created_by_email TEXT,
      created_at TEXT,
      updated_at TEXT
    )`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.sale_deal_agents (
      sale_deal_id INTEGER NOT NULL REFERENCES portal.sale_deals(id) ON DELETE CASCADE,
      agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
      share_pct DOUBLE PRECISION NOT NULL,
      is_primary BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT,
      PRIMARY KEY (sale_deal_id, agent_id)
    )`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_sale_deal_agents_agent
      ON portal.sale_deal_agents(agent_id)`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.invoices (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      building_id INTEGER REFERENCES portal.buildings(id),
      rental_deal_id INTEGER REFERENCES portal.rental_deals(id) ON DELETE SET NULL,
      invoice_number TEXT NOT NULL,
      file_name TEXT NOT NULL,
      email_subject TEXT,
      unit TEXT NOT NULL,
      tenant_name TEXT NOT NULL,
      agent_email TEXT,
      agent_name TEXT,
      agent_phone TEXT,
      apartment_address TEXT,
      move_in_date TEXT,
      licensed_company TEXT NOT NULL,
      year INTEGER NOT NULL DEFAULT 2026,
      line_items JSONB,
      total_amount DOUBLE PRECISION NOT NULL,
      notes TEXT,
      status TEXT NOT NULL DEFAULT 'draft',
      sent_at TEXT,
      paid_at TEXT,
      paid_amount DOUBLE PRECISION,
      pdf_data TEXT,
      created_at TEXT,
      updated_at TEXT
    )`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.invoice_send_log (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      invoice_id INTEGER NOT NULL REFERENCES portal.invoices(id) ON DELETE CASCADE,
      sent_by_email TEXT,
      to_recipients TEXT NOT NULL,
      cc_recipients TEXT,
      reply_to TEXT,
      subject TEXT NOT NULL,
      status TEXT NOT NULL,
      error_message TEXT,
      sent_at TEXT
    )`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_invoice_send_log_invoice
      ON portal.invoice_send_log(invoice_id)`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.commerce_orders (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      product_key TEXT NOT NULL,
      product_name TEXT NOT NULL,
      billing_mode TEXT NOT NULL,
      stripe_price_id TEXT,
      amount_cents INTEGER NOT NULL,
      currency TEXT NOT NULL DEFAULT 'usd',
      status TEXT NOT NULL DEFAULT 'pending',
      stripe_checkout_session_id TEXT UNIQUE,
      stripe_customer_id TEXT,
      stripe_subscription_id TEXT,
      stripe_payment_intent_id TEXT,
      checkout_url TEXT,
      customer_name TEXT,
      customer_email TEXT,
      requested_workspace_email TEXT,
      phone TEXT,
      referral_has_agent TEXT,
      referral_agent_name TEXT,
      message TEXT,
      workspace_status TEXT NOT NULL DEFAULT 'not_required',
      workspace_user_id TEXT,
      workspace_error TEXT,
      paid_at TEXT,
      created_at TEXT,
      updated_at TEXT
    )`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_commerce_orders_subscription
      ON portal.commerce_orders(stripe_subscription_id)`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_commerce_orders_customer_email
      ON portal.commerce_orders(customer_email)`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.stripe_events (
      id TEXT PRIMARY KEY,
      type TEXT NOT NULL,
      commerce_order_id INTEGER REFERENCES portal.commerce_orders(id) ON DELETE SET NULL,
      received_at TEXT
    )`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.commerce_charges (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      commerce_order_id INTEGER REFERENCES portal.commerce_orders(id) ON DELETE SET NULL,
      stripe_invoice_id TEXT NOT NULL UNIQUE,
      stripe_subscription_id TEXT,
      stripe_customer_id TEXT,
      amount_cents INTEGER NOT NULL,
      currency TEXT NOT NULL DEFAULT 'usd',
      status TEXT NOT NULL,
      product_name TEXT,
      customer_email TEXT,
      customer_name TEXT,
      period_start TEXT,
      period_end TEXT,
      paid_at TEXT,
      created_at TEXT
    )`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_commerce_charges_paid_at
      ON portal.commerce_charges(paid_at)`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_commerce_charges_subscription
      ON portal.commerce_charges(stripe_subscription_id)`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.training_videos (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      title TEXT NOT NULL,
      description TEXT,
      category TEXT NOT NULL DEFAULT 'General',
      cloudflare_uid TEXT NOT NULL,
      duration_label TEXT,
      sort_order INTEGER NOT NULL DEFAULT 100,
      is_published BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TEXT,
      updated_at TEXT
    )`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.training_video_views (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      video_id INTEGER NOT NULL REFERENCES portal.training_videos(id) ON DELETE CASCADE,
      agent_id INTEGER REFERENCES portal.agents(id) ON DELETE SET NULL,
      agent_email TEXT NOT NULL,
      first_viewed_at TEXT NOT NULL,
      last_viewed_at TEXT NOT NULL,
      open_count INTEGER NOT NULL DEFAULT 1,
      created_at TEXT,
      updated_at TEXT
    )`);
  await run(`
    CREATE UNIQUE INDEX IF NOT EXISTS idx_training_video_views_unique_viewer
      ON portal.training_video_views(video_id, agent_email)`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_training_video_views_agent
      ON portal.training_video_views(agent_email)`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.resources (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      title TEXT NOT NULL,
      description TEXT,
      category TEXT NOT NULL DEFAULT 'General',
      url TEXT NOT NULL,
      sample_url TEXT,
      sort_order INTEGER NOT NULL DEFAULT 100,
      is_published BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TEXT,
      updated_at TEXT
    )`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.checklist_items (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      group_key TEXT NOT NULL,
      label TEXT NOT NULL,
      sort_order INTEGER NOT NULL DEFAULT 100,
      created_at TEXT,
      updated_at TEXT
    )`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_checklist_items_group
      ON portal.checklist_items(group_key)`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.notifications (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      recipient_agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE CASCADE,
      type TEXT NOT NULL,
      title TEXT NOT NULL,
      body TEXT,
      href TEXT,
      dedupe_key TEXT UNIQUE,
      read_at TEXT,
      created_at TEXT
    )`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_notifications_recipient
      ON portal.notifications(recipient_agent_id, read_at)`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.audit_log (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      actor_email TEXT,
      action TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id TEXT,
      summary TEXT NOT NULL,
      detail TEXT,
      created_at TEXT
    )`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_audit_log_entity
      ON portal.audit_log(entity_type, entity_id)`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.deal_documents (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      deal_type TEXT NOT NULL,
      deal_id INTEGER NOT NULL,
      file_name TEXT NOT NULL,
      url TEXT NOT NULL DEFAULT '',
      storage_provider TEXT NOT NULL DEFAULT 'r2',
      object_key TEXT NOT NULL DEFAULT '',
      content_type TEXT,
      size INTEGER,
      uploaded_by_email TEXT,
      checklist_item_id INTEGER,
      created_at TEXT
    )`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_deal_documents_deal
      ON portal.deal_documents(deal_type, deal_id)`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_deal_documents_object_key
      ON portal.deal_documents(object_key)`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.agent_payment_profiles (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      agent_id INTEGER NOT NULL UNIQUE REFERENCES portal.agents(id) ON DELETE CASCADE,
      payee_type TEXT,
      payee_name TEXT,
      bank_name TEXT,
      account_type TEXT,
      routing_number TEXT,
      account_number TEXT,
      w9_object_key TEXT,
      w9_file_name TEXT,
      w9_uploaded_at TEXT,
      updated_at TEXT
    )`);

  await run(`
    CREATE TABLE IF NOT EXISTS portal.agent_payouts (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE CASCADE,
      amount_cents INTEGER NOT NULL,
      method TEXT NOT NULL DEFAULT 'ach',
      reference TEXT,
      memo TEXT,
      deal_type TEXT,
      deal_id INTEGER,
      paid_at TEXT NOT NULL,
      created_by_email TEXT,
      created_at TEXT,
      updated_at TEXT
    )`);
  await run(`
    CREATE INDEX IF NOT EXISTS idx_agent_payouts_agent_paid
      ON portal.agent_payouts(agent_id, paid_at DESC)`);

  // ---- Future column additions go here, mirroring the old pattern: ----
  // await run(`ALTER TABLE portal.xxx ADD COLUMN IF NOT EXISTS yyy TEXT`);

  console.log("Portal schema ensured.");
}
