import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import * as schema from "./schema";
import { buildings, settings } from "./schema";

const client = createClient({
  url: process.env.TURSO_DATABASE_URL || "file:local.db",
  authToken: process.env.TURSO_AUTH_TOKEN,
});

const db = drizzle(client, { schema });

// ============================================================
// 汇总 Sheet — 所有大楼数据（350+ buildings from Google Sheets）
// ============================================================
const buildingsData: schema.NewBuilding[] = [
  // ============================================================
  // RI
  // ============================================================
  {
    region: "RI",
    name: "The Octagon",
    managementCompany: "Greystar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-OCTAGON-{year}",
    billToCompany: "The Octagon",
    billToAddress: "888 Main st, New York, NY 10044",
  },

  // ============================================================
  // 中城 — Greystar 管理
  // ============================================================
  {
    region: "中城",
    name: "The Biltmore",
    managementCompany: "Greystar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BILTMORE-{year}",
    billToCompany: "The Biltmore",
    billToAddress: "271 W 47th St, New York, NY 10036",
  },
  {
    region: "中城",
    name: "Henry Hall",
    managementCompany: "Greystar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HENRY HALL-{year}",
    billToCompany: "Henry Hall",
    billToAddress: "515 W 38th St, New York, NY 10018",
  },
  {
    region: "中城",
    name: "The Chelsea",
    managementCompany: "Greystar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE CHELSEA-{year}",
    billToCompany: "The Chelsea",
    billToAddress: "160 W 25th St, New York, NY 10011",
  },
  {
    region: "中城",
    name: "Oriana",
    managementCompany: "Greystar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ORIANA-{year}",
    billToCompany: "Oriana",
    billToAddress: "430 E 54th St, New York, NY 10022",
  },
  {
    region: "中城",
    name: "The Dylan",
    managementCompany: "Greystar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-DYLAN-{year}",
    billToCompany: "Greystar Management",
    billToAddress: "280 Park Ave #14a, New York, NY 10017",
  },
  {
    region: "中城",
    name: "19 Dutch",
    submissionType: "email",
    invoiceNumberFormat: "Unit-19 DUTCH-{year}",
    billToCompany: "19 Dutch",
    billToAddress: "19 Dutch St, New York, NY 10038",
  },

  // ============================================================
  // 中城 — Heritage Collection
  // ============================================================
  {
    region: "中城",
    name: "111 E 30th St - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-111E30TH-HC-{year}",
    billToCompany: "Heritage Collection Midtown LLC",
    billToAddress: "308 W 18th St, New York, NY 10011",
  },
  {
    region: "中城",
    name: "115 East 37th Street - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-115E37-HC-{year}",
    billToCompany: "Heritage Collection Midtown LLC",
    billToAddress: "308 W 18th St, New York, NY 10011",
  },
  {
    region: "中城",
    name: "135 E 37th Street - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-135E37-HC-{year}",
    billToCompany: "Heritage Collection Midtown LLC",
    billToAddress: "308 W 18th St, New York, NY 10011",
  },
  {
    region: "中城",
    name: "141 E 36th Street - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-141E36-HC-{year}",
    billToCompany: "Heritage Collection Midtown LLC",
    billToAddress: "308 W 18th St, New York, NY 10011",
  },
  {
    region: "中城",
    name: "305 East 18th St - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-305E18-HC-{year}",
    billToCompany: "Heritage Collection Midtown LLC",
    billToAddress: "308 W 18th St, New York, NY 10011",
  },
  {
    region: "中城",
    name: "200 E 62nd St - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-200E62-HC-{year}",
    billToCompany: "Heritage Collection Midtown LLC",
    billToAddress: "308 W 18th St, New York, NY 10011",
  },
  {
    region: "中城",
    name: "102 W 18th St - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-102W18-HC-{year}",
    billToCompany: "Heritage Collection Midtown LLC",
    billToAddress: "308 W 18th St, New York, NY 10011",
  },
  {
    region: "中城",
    name: "308 W 18th St - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-308W18-HC-{year}",
    billToCompany: "Heritage Collection Midtown LLC",
    billToAddress: "308 W 18th St, New York, NY 10011",
  },
  {
    region: "中城",
    name: "336 East 15th Street - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-336E15-HC-{year}",
    billToCompany: "Heritage Collection",
  },
  {
    region: "中城",
    name: "3 East 7th Street - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-3E07-HC-{year}",
    billToCompany: "Heritage Collection",
  },
  {
    region: "中城",
    name: "85 2nd Ave - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-85 2 AVE-HC-{year}",
    billToCompany: "Heritage Collection",
  },
  {
    region: "中城",
    name: "81 Sullivan St-Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-81 SULV-HC-{year}",
    billToCompany: "Spruce LLC",
  },
  {
    region: "中城",
    name: "230 Sullivan St-Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-230 SULV-HC-{year}",
    billToCompany: "Heritage Collection",
  },
  {
    region: "中城",
    name: "235 Sullivan St-Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-235 SULV-HC-{year}",
    billToCompany: "Heritage Collection",
  },
  {
    region: "中城",
    name: "139 W 91 St - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-139W91-HC-{year}",
    billToCompany: "Heritage Collection",
  },
  {
    region: "中城",
    name: "176 Bleecker St - Heritage Collection",
    managementCompany: "Heritage Collection",
    submissionType: "email",
    invoiceNumberFormat: "Unit-176 BLCK-HC-{year}",
    billToCompany: "Heritage Collection",
  },

  // ============================================================
  // 中城 — TFC (TF Cornerstone) - portal上传
  // ============================================================
  {
    region: "中城",
    name: "606 W 57th St",
    managementCompany: "TF Cornerstone",
    submissionType: "email",
    submissionNotes: "大楼 portal 上传",
    invoiceNumberFormat: "Unit-606W57-{year}",
    billToCompany: "TF Cornerstone, Inc",
    billToAddress: "367 Park Avenue South, New York, NY 10016",
  },
  {
    region: "中城",
    name: "505W37",
    managementCompany: "TF Cornerstone",
    submissionType: "email",
    submissionNotes: "大楼 portal 上传",
    invoiceNumberFormat: "Unit-505W37-{year}",
    billToCompany: "TF Cornerstone, Inc",
    billToAddress: "367 Park Avenue South, New York, NY 10016",
  },
  {
    region: "中城",
    name: "2 Gold St",
    managementCompany: "TF Cornerstone",
    submissionType: "email",
    submissionNotes: "大楼 portal 上传",
    invoiceNumberFormat: "Unit-2GOLD-{year}",
    billToCompany: "TF Cornerstone, Inc",
    billToAddress: "367 Park Avenue South, New York, NY 10016",
  },
  {
    region: "中城",
    name: "45 Wall Street",
    managementCompany: "TF Cornerstone",
    submissionType: "email",
    submissionNotes: "大楼 portal 上传",
    invoiceNumberFormat: "Unit-45WALL-{year}",
    billToCompany: "TF Cornerstone, Inc",
    billToAddress: "367 Park Avenue South, New York, NY 10016",
  },

  // ============================================================
  // 中城 — Kips Bay Court - 大楼portal上传
  // ============================================================
  {
    region: "中城",
    name: "Kips Bay Court 460 Second Ave",
    submissionType: "email",
    submissionNotes: "大楼portal上传",
    invoiceNumberFormat: "Unit-Kips Bay Court 460 Second Ave-{year}",
    billToCompany: "Kips Bay Court",
    billToAddress: "490 2nd Ave, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Kips Bay Court 470 Second Ave",
    submissionType: "email",
    submissionNotes: "大楼portal上传",
    invoiceNumberFormat: "Unit-Kips Bay Court 470 Second Ave-{year}",
    billToCompany: "Kips Bay Court",
    billToAddress: "490 2nd Ave, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Kips Bay Court 480 Second Ave",
    submissionType: "email",
    submissionNotes: "大楼portal上传",
    invoiceNumberFormat: "Unit-Kips Bay Court 480 Second Ave-{year}",
    billToCompany: "Kips Bay Court",
    billToAddress: "490 2nd Ave, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Kips Bay Court 484 Second Ave",
    submissionType: "email",
    submissionNotes: "大楼portal上传",
    invoiceNumberFormat: "Unit-Kips Bay Court 484 Second Ave-{year}",
    billToCompany: "Kips Bay Court",
    billToAddress: "490 2nd Ave, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Kips Bay Court 490 Second Ave",
    submissionType: "email",
    submissionNotes: "大楼portal上传",
    invoiceNumberFormat: "Unit-Kips Bay Court 490 Second Ave-{year}",
    billToCompany: "Kips Bay Court",
    billToAddress: "490 2nd Ave, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Kips Bay Court 500 Second Ave",
    submissionType: "email",
    submissionNotes: "大楼portal上传",
    invoiceNumberFormat: "Unit-Kips Bay Court 500 Second Ave-{year}",
    billToCompany: "Kips Bay Court",
    billToAddress: "490 2nd Ave, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Kips Bay Court 510 Second Ave",
    submissionType: "email",
    submissionNotes: "大楼portal上传",
    invoiceNumberFormat: "Unit-Kips Bay Court 510 Second Ave-{year}",
    billToCompany: "Kips Bay Court",
    billToAddress: "490 2nd Ave, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Kips Bay Court 520 Second Ave",
    submissionType: "email",
    submissionNotes: "大楼portal上传",
    invoiceNumberFormat: "Unit-Kips Bay Court 520 Second Ave-{year}",
    billToCompany: "Kips Bay Court",
    billToAddress: "490 2nd Ave, New York, NY 10016",
  },

  // ============================================================
  // 中城 — Other buildings
  // ============================================================
  {
    region: "中城",
    name: "1080 Amsterdam",
    submissionType: "email",
    invoiceNumberFormat: "Unit-1080 AMSTERDAM-{year}",
    billToCompany: "A&E Real Estate Management",
    billToAddress: "40 W 57th Street, Suite 1720, New York, NY 10019",
  },
  {
    region: "中城",
    name: "Sunrise Tower",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SUNRISE TOWER-{year}",
    billToCompany: "Bohemia Realty Group LLC",
    billToAddress: "630 W 153rd St, New York, NY 10031",
  },
  {
    region: "中城",
    name: "The Westmont Apartments",
    submissionType: "email",
    invoiceNumberFormat: "Unit-WESTMONT-{year}",
    billToCompany: "The Westmont Apartments",
    billToAddress: "730 Columbus Ave, New York, NY 10025",
  },
  {
    region: "中城",
    name: "784 Columbus Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PWV 784-{year}",
    billToCompany: "PWV Acquisition LLC",
    billToAddress: "792 Columbus Avenue, New York, NY 10025",
  },
  {
    region: "中城",
    name: "786 Columbus Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PWV 786-{year}",
    billToCompany: "PWV Acquisition LLC",
    billToAddress: "792 Columbus Avenue, New York, NY 10025",
  },
  {
    region: "中城",
    name: "792 Columbus Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PWV 792-{year}",
    billToCompany: "PWV Acquisition LLC",
    billToAddress: "792 Columbus Avenue, New York, NY 10025",
  },
  {
    region: "中城",
    name: "805 Columbus",
    submissionType: "email",
    invoiceNumberFormat: "Unit-805 COLUMBUS-{year}",
    billToCompany: "Columbus Square Management",
    billToAddress: "805 Columbus Ave, New York, NY 10025",
  },
  {
    region: "中城",
    name: "808 Columbus",
    submissionType: "email",
    invoiceNumberFormat: "Unit-808 COLUMBUS-{year}",
    billToCompany: "Columbus Square Management",
    billToAddress: "808 Columbus Ave, New York, NY 10025",
  },
  {
    region: "中城",
    name: "915 West End Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-915 WEST END-{year}",
    billToCompany: "915 West End Owner II LLC",
    billToAddress: "915 West End Ave, New York, NY 10025",
  },
  {
    region: "中城",
    name: "931 Amsterdam Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-931 AMSTERDAM-{year}",
    billToCompany: "",
    billToAddress: "931 Amsterdam Ave, New York, NY 10025",
  },
  {
    region: "中城",
    name: "4050 BROADWAY",
    submissionType: "email",
    invoiceNumberFormat: "Unit-4050 BROADWAY-{year}",
    billToCompany: "ASCOT INWOOD LLC",
    billToAddress: "4050 Broadway, New York, NY 10034",
  },
  {
    region: "中城",
    name: "1440 Amsterdam Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-1440 AMSTERDAM-{year}",
    billToCompany: "1440 Owner LLC",
    billToAddress: "316 W 118th Street, New York, NY 10026",
  },
  {
    region: "中城",
    name: "Hotel 91",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HOTEL 91-{year}",
    billToCompany: "Hotel 91 LLC",
    billToAddress: "244 West 91th St, New York, NY 10025",
  },
  {
    region: "中城",
    name: "Victoria Tower Residences",
    submissionType: "email",
    invoiceNumberFormat: "Unit-VICTORIA TOWER-{year}",
    billToCompany: "230 West 125th Street Danforth LLC",
  },
  {
    region: "中城",
    name: "101 West End Avenue",
    submissionType: "email",
    invoiceNumberFormat: "Unit-101 WEST END-{year}",
    billToCompany: "101 West End REIT LLC",
    billToAddress: "101 West End Ave, New York, NY 10023",
  },
  {
    region: "中城",
    name: "21 West End Avenue",
    submissionType: "email",
    invoiceNumberFormat: "Unit-21 WEST END-{year}",
    billToCompany: "101 West End REIT LLC",
    billToAddress: "101 West End Ave, New York, NY 10023",
  },
  {
    region: "中城",
    name: "Mercedes House",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MH-{year}",
    billToCompany: "MH Rentals, LLC",
    billToAddress: "550 W 54th St, New York, NY 10019",
  },
  {
    region: "中城",
    name: "Instrata at Mercedes House",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MH-{year}",
    billToCompany: "Instrata Real Estate",
    billToAddress: "550 W 54th St, New York, NY 10019",
  },
  {
    region: "中城",
    name: "Aire",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AIRE-{year}",
    billToCompany: "GOTHAM DEVELOPER OWNER MANAGER",
    billToAddress: "200 West 67th Street, New York, NY 10023",
  },
  {
    region: "中城",
    name: "Midtown Court",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MC-{year}",
    billToCompany: "Midwest Court LLC",
    billToAddress: "410 West 53rd St, New York, NY 10019",
  },
  {
    region: "中城",
    name: "One Waterline Square",
    submissionType: "email",
    invoiceNumberFormat: "Unit-1 WATERLINE SQ-{year}",
    billToCompany: "One Waterline Square Luxury Rentals",
    billToAddress: "675 W 59th St, New York, NY 10019",
  },
  {
    region: "中城",
    name: "Two Waterline Square",
    submissionType: "email",
    invoiceNumberFormat: "Unit-2 WATERLINE SQ-{year}",
    billToCompany: "Two Waterline Square Luxury Rentals",
    billToAddress: "400 West 61st St, New York, NY 10069",
  },
  {
    region: "中城",
    name: "Three Waterline Square",
    submissionType: "email",
    invoiceNumberFormat: "Unit-3 WATERLINE SQ-{year}",
    billToCompany: "Three Waterline Square Luxury Rentals",
    billToAddress: "400 West 61st St, New York, NY 10069",
  },
  {
    region: "中城",
    name: "VIA 57 West",
    submissionType: "email",
    invoiceNumberFormat: "Unit-VIA 57-{year}",
    billToCompany: "VIA 57 Durst Residential Properties",
    billToAddress: "625 W 57th Street, New York, NY 10019",
  },
  {
    region: "中城",
    name: "20 Waterside Plaza",
    submissionType: "email",
    invoiceNumberFormat: "Unit-20 WATERSIDE PL-{year}",
    billToCompany: "Waterside Plaza",
    billToAddress: "20 Waterside Plaza, New York, NY 10010",
  },
  {
    region: "中城",
    name: "30 Waterside Plaza",
    submissionType: "email",
    invoiceNumberFormat: "Unit-30 WATERSIDE PL-{year}",
    billToCompany: "Waterside Plaza",
    billToAddress: "30 Waterside Plaza, New York, NY 10012",
  },
  {
    region: "中城",
    name: "555TEN",
    submissionType: "email",
    invoiceNumberFormat: "Unit-555TEN-{year}",
    billToCompany: "",
    billToAddress: "555 10th Ave, New York, NY 10018",
  },
  {
    region: "中城",
    name: "The Copper",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE COPPER-{year}",
    billToCompany: "American Copper LLC",
    billToAddress: "626 1st Ave, New York, NY 10016",
  },
  {
    region: "中城",
    name: "685 First Avenue",
    submissionType: "email",
    invoiceNumberFormat: "Unit-685 FIRST AVE-{year}",
    billToCompany: "",
    billToAddress: "685 First Avenue, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Anagram NoMad",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ANAGRAM NOMAD-{year}",
    billToCompany: "",
    billToAddress: "10 E 29th St, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Atlas New York",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ATLAS NY-{year}",
    billToCompany: "1010 6th Associates, LLC",
    billToAddress: "66 W 38th St, New York, NY 10018",
  },
  {
    region: "中城",
    name: "Avalon Clinton",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AVA CLINTON-{year}",
    billToCompany: "Avalon Clinton",
    billToAddress: "515 W 52nd St, New York, NY 10019",
  },
  {
    region: "中城",
    name: "136 East 56th Street",
    submissionType: "email",
    invoiceNumberFormat: "Unit-136 E 55-{year}",
    billToCompany: "",
    billToAddress: "136 East 56th Street, Suite 8J, New York, NY 10022",
  },
  {
    region: "中城",
    name: "EOS",
    submissionType: "email",
    invoiceNumberFormat: "Unit-EOS-{year}",
    billToCompany: "EOS MRU LLC",
    billToAddress: "100 W 31st St, New York, NY 10001",
  },
  {
    region: "中城",
    name: "Gotham West",
    submissionType: "email",
    invoiceNumberFormat: "Unit-GOTHAM WEST-{year}",
    billToCompany: "Gotham West",
    billToAddress: "550 West 45th St, New York, NY 10036",
  },
  {
    region: "中城",
    name: "The Maybury",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MAYBURY-{year}",
    billToCompany: "GO Covenant LLC",
    billToAddress: "550 10th Ave, New York, NY 10018",
  },
  {
    region: "中城",
    name: "606 W 30",
    submissionType: "email",
    invoiceNumberFormat: "Unit-606W30-{year}",
    billToCompany: "West 30th Street LLC",
    billToAddress: "606 W 30th St, New York, NY 10001",
  },
  {
    region: "中城",
    name: "Herald Towers",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HERALD TOWERS-{year}",
    billToCompany: "Herald Towers",
    billToAddress: "50 W 34th St, New York, NY 10001",
  },
  {
    region: "中城",
    name: "Hollingsworth",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HOLLINGSWORTH-{year}",
    billToCompany: "VRG 990 ACA LLC",
    billToAddress: "70 W 37th St, New York, NY 10018",
  },
  {
    region: "中城",
    name: "House 39",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HOUSE 39-{year}",
    billToCompany: "House 39",
    billToAddress: "225 E 39th St, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Lynn NYC",
    submissionType: "email",
    invoiceNumberFormat: "Unit-LYNN-{year}",
    billToCompany: "",
    billToAddress: "15 East 28th Street, 7th Floor, New York, NY 10016",
  },
  {
    region: "中城",
    name: "Oskar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-OSKAR-{year}",
    billToCompany: "Oskar",
    billToAddress: "572 11th Ave, New York, NY 10036",
  },
  {
    region: "中城",
    name: "Ruby",
    submissionType: "email",
    invoiceNumberFormat: "Unit-RUBY-{year}",
    billToCompany: "241 West 28th Street Owner LLC",
    billToAddress: "241 West 28th Street, New York, NY 10001",
  },
  {
    region: "中城",
    name: "Silver Towers",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SILVER TOWERS-{year}",
    billToCompany: "Silverstein Properties LLC",
    billToAddress: "620 W 42nd St, New York, NY 10036",
  },
  {
    region: "中城",
    name: "Sky",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SKY-{year}",
    billToCompany: "605 West 42nd Owner LLC",
    billToAddress: "605 W 42nd St, New York, NY 10036",
  },
  {
    region: "中城",
    name: "Solar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SOLAR-{year}",
    billToCompany: "Solar",
    billToAddress: "42 W 33rd St, New York, NY 10001",
  },
  {
    region: "中城",
    name: "The Continental",
    submissionType: "email",
    invoiceNumberFormat: "Unit-CONTINENTAL-{year}",
    billToCompany: "Tower 111 LLC",
    billToAddress: "885 6th Ave, New York, NY 10001",
  },
  {
    region: "中城",
    name: "The Epic",
    submissionType: "email",
    invoiceNumberFormat: "Unit-EPIC-{year}",
    billToCompany: "",
    billToAddress: "780 Third Avenue, Suite 401, New York, NY 10017",
  },
  {
    region: "中城",
    name: "The Howell",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HOWELL-{year}",
    billToCompany: "84 William Street Property Owner LLC",
    billToAddress: "84 William St, New York, NY 10038",
  },
  {
    region: "中城",
    name: "The Landon",
    submissionType: "email",
    invoiceNumberFormat: "Unit-LANDON-{year}",
    billToCompany: "",
    billToAddress: "520 West 43rd Street, New York, NY 10036",
  },
  {
    region: "中城",
    name: "The Ritz Plaza",
    submissionType: "email",
    invoiceNumberFormat: "Unit-RITZ PLAZA-{year}",
    billToCompany: "CS RITZ RESIDENCES LLC",
    billToAddress: "1675 Broadway 21st floor, New York, NY 10019",
  },
  {
    region: "中城",
    name: "The Victory",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE VICTORY-{year}",
    billToCompany: "ESRT Victory Owner, LLC",
    billToAddress: "561 10th Ave, New York, NY 10036",
  },
  {
    region: "中城",
    name: "Union Square Inn",
    submissionType: "email",
    invoiceNumberFormat: "Unit-UNION SQ INN-{year}",
    billToCompany: "Best Inns USA LLC",
    billToAddress: "209 E 14th Street, New York NY 10003",
  },
  {
    region: "中城",
    name: "SoMa",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SOMA-{year}",
    billToCompany: "EOS 25 Water Owner LLC",
    billToAddress: "25 Water St, New York, NY 10004",
  },
  {
    region: "中城",
    name: "20 Broad",
    submissionType: "email",
    invoiceNumberFormat: "Unit-20 BROAD-{year}",
    billToCompany: "20 Broad Street Owner LLC",
    billToAddress: "20 Broad Street, New York, NY 11101",
  },
  {
    region: "中城",
    name: "One Manhattan Square",
    submissionType: "email",
    invoiceNumberFormat: "Unit-OMS-{year}",
    billToCompany: "CPS Fee Company III LLC",
    billToAddress: "225 Cherry St, New York, NY 10002",
  },
  {
    region: "中城",
    name: "EVE East Village",
    submissionType: "email",
    invoiceNumberFormat: "Unit-EVE EAST-{year}",
    billToCompany: "East 14th Street Owner LLC",
    billToAddress: "433 East 11th St, New York, NY 10009",
  },
  {
    region: "中城",
    name: "EVSB 510",
    submissionType: "email",
    invoiceNumberFormat: "Unit-EVSB 510-{year}",
    billToCompany: "East Village 14 Owner",
    billToAddress: "510 E 14th St, New York, NY 10009",
  },
  {
    region: "中城",
    name: "The Suffolk",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SUFFOLK-{year}",
    billToCompany: "GO Broome LLC",
    billToAddress: "55 Suffolk Street, New York, NY 10002",
  },
  {
    region: "中城",
    name: "Pearl House",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PEARL HOUSE-{year}",
    billToCompany: "",
    billToAddress: "160 Water St, New York, NY 10038",
  },

  // ============================================================
  // 中城 — MMA (Related Rentals)
  // ============================================================
  {
    region: "中城",
    name: "MMA",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MMA-{year}",
    billToCompany: "Mima, Related Rentals",
    billToAddress: "450 W 42nd St, New York, NY 10036",
  },

  // ============================================================
  // 中城 — The Ellery
  // ============================================================
  {
    region: "中城",
    name: "The Ellery",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE ELLERY-{year}",
    billToCompany: "311 West 42nd Street Associates LLC",
    billToAddress: "312 W 43rd St, New York, NY 10036",
  },

  // ============================================================
  // 上城
  // ============================================================
  {
    region: "上城",
    name: "James Marquis Apartments",
    submissionType: "email",
    invoiceNumberFormat: "Unit-JAMES MARQUIS-{year}",
    billToCompany: "James Marquis Apartments",
    billToAddress: "101 W 90th St, New York, NY 10024",
  },
  {
    region: "上城",
    name: "120 West 105th Street",
    submissionType: "email",
    invoiceNumberFormat: "Unit-120 W 105-{year}",
    billToCompany: "",
    billToAddress: "120 W 105th St, New York, NY 10025",
  },
  {
    region: "上城",
    name: "Fortress at Columbus",
    submissionType: "email",
    invoiceNumberFormat: "Unit-FORTRESS-{year}",
    billToCompany: "Columbia International LLC",
    billToAddress: "347 5th Ave #1403, New York, NY 10016",
  },
  {
    region: "上城",
    name: "The Smile - Loft Residences in Harlem",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE SMILE-{year}",
    billToCompany: "BDG Gotham Residential LLC (The Smile)",
    billToAddress: "158 East 126th St, New York, NY 10035",
  },
  {
    region: "上城",
    name: "211 West 106th Street",
    submissionType: "email",
    invoiceNumberFormat: "Unit-211 W 106-{year}",
    billToCompany: "211 West 106th Apartment",
    billToAddress: "211 W 106th St, New York, NY 10025",
  },
  {
    region: "上城",
    name: "The Greystone",
    submissionType: "email",
    invoiceNumberFormat: "Unit-GREYSTONE-{year}",
    billToCompany: "Broadway Greystone LLC",
    billToAddress: "212 W 91st St, New York, NY 10024",
  },
  {
    region: "上城",
    name: "Midway Hotel",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MIDWAY HOTEL-{year}",
    billToCompany: "Midway Hotel",
    billToAddress: "216 W 100th St, New York, NY 10025",
  },
  {
    region: "上城",
    name: "218 W 108th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-218 W 108-{year}",
    billToCompany: "Grace Manor NYC",
    billToAddress: "218 W 108th St, New York, NY 10025",
  },
  {
    region: "上城",
    name: "Central Park Apartment",
    submissionType: "email",
    invoiceNumberFormat: "Unit-19 W 103-{year}",
    billToCompany: "Jona Manhattan Realty",
    billToAddress: "209 E 14 street, New York, NY 10009",
  },
  {
    region: "上城",
    name: "224 W 124th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-224 W 124-{year}",
    billToCompany: "Rose Associates Inc",
    billToAddress: "200 West 83rd Street, New York, NY 11232",
  },
  {
    region: "上城",
    name: "The Milan",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MILAN-{year}",
    billToCompany: "",
    billToAddress: "290 West 83rd Street, New York, NY 10025",
  },
  {
    region: "上城",
    name: "30 Morningside Drive",
    submissionType: "email",
    invoiceNumberFormat: "Unit-30 MSD-{year}",
    billToCompany: "30 Morningside Master Tenant LLC",
    billToAddress: "30 Morningside Dr, New York, NY 10025",
  },
  {
    region: "上城",
    name: "Hudson Park",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HUDSON PARK-{year}",
    billToCompany: "Hudson Park NY LLC",
    billToAddress: "323 West 96th Street, New York, NY 10025",
  },
  {
    region: "上城",
    name: "Enclave at the Cathedral",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ENCLAVE-{year}",
    billToCompany: "Enclave at the Cathedral",
    billToAddress: "400 W 113th St, New York, NY 10025",
  },
  {
    region: "上城",
    name: "Monarch Heights",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MONARCH HEIGHTS-{year}",
    billToCompany: "Monarch Heights LLC",
    billToAddress: "415 West 120th Street, New York, NY 10027",
  },

  // ============================================================
  // 上城 — Stellar managed
  // ============================================================
  {
    region: "上城",
    name: "50 W 93rd St",
    managementCompany: "Stellar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-50 W 93-{year}",
    billToCompany: "Stellar Management LLC",
    billToAddress: "50 W 97th St, New York, NY 10025",
  },
  {
    region: "上城",
    name: "Central Park Gardens",
    managementCompany: "Stellar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-50 W 97-{year}",
    billToCompany: "Stellar Management LLC",
    billToAddress: "50 W 97th St, New York, NY 10025",
  },
  {
    region: "上城",
    name: "70 W 93rd St",
    managementCompany: "Stellar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-70 W 93-{year}",
    billToCompany: "Stellar Management LLC",
    billToAddress: "70 W 93rd St, New York, NY 10025",
  },
  {
    region: "上城",
    name: "The Paris New York",
    managementCompany: "Stellar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PARIS NY-{year}",
    billToCompany: "Stellar Management LLC",
    billToAddress: "156 William Street 10th Fl, New York, NY 10038",
  },
  {
    region: "上城",
    name: "Windermere",
    managementCompany: "Stellar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-WINDERMERE-{year}",
    billToCompany: "",
    billToAddress: "666 West End Ave, New York, NY 10025",
  },

  // ============================================================
  // 上城 — more
  // ============================================================
  {
    region: "上城",
    name: "Inwood",
    submissionType: "email",
    invoiceNumberFormat: "Unit-INWOOD LIVING-{year}",
    billToCompany: "The Joy Group Inc.",
    billToAddress: "84 Knickerbocker St, Brooklyn, NY 11235",
  },
  {
    region: "上城",
    name: "Ray Harlem",
    submissionType: "email",
    invoiceNumberFormat: "Unit-RAY HARLEM-{year}",
    billToCompany: "2033 National Black Theatre Way LLC",
    billToAddress: "2035 Fifth Ave, New York, NY 10035",
  },
  {
    region: "上城",
    name: "Carnegie Hill Place",
    submissionType: "email",
    invoiceNumberFormat: "Unit-CARNEGIE HILL PLACE-{year}",
    billToCompany: "1500 Lexington Associates LLC",
    billToAddress: "1500 Lexington Avenue, New York, NY 10029",
  },
  {
    region: "上城",
    name: "The Lyric Luxury Apartments",
    submissionType: "email",
    invoiceNumberFormat: "Unit-LYRIC-{year}",
    billToCompany: "Related Rentals",
    billToAddress: "255 W 94th St, New York, NY 10025",
  },
  {
    region: "上城",
    name: "Avalon Morningside Park",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AVA MSD PARK-{year}",
    billToCompany: "Avalon Morningside Park",
    billToAddress: "1 Morningside Dr, New York, NY 10025",
  },

  // ============================================================
  // 西
  // ============================================================
  {
    region: "西",
    name: "MIRAMAR LOT9",
    submissionType: "email",
    invoiceNumberFormat: "Unit- MIRAMAR LOT9-{year}",
    billToCompany: "Inwood Lot 9 Development Associates LLC",
    billToAddress: "407 W 206th St, New York, NY 10034",
  },
  {
    region: "西",
    name: "MIRAMAR LOT21",
    submissionType: "email",
    invoiceNumberFormat: "Unit- MIRAMAR LOT21-{year}",
    billToCompany: "Harlem River Ninth Avenue Development LLC",
    billToAddress: "405 W 206th St, New York, NY 10034",
  },

  // ============================================================
  // RI — Manhattan Park
  // ============================================================
  {
    region: "RI",
    name: "Manhattan Park 10",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MP 10-{year}",
    billToCompany: "ROOSEVELT ISLAND ASSOCIATES",
    billToAddress: "30 River Rd, New York, NY 10044",
  },
  {
    region: "RI",
    name: "Manhattan Park 20",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MP 20-{year}",
    billToCompany: "ROOSEVELT ISLAND ASSOCIATES",
    billToAddress: "30 River Rd, New York, NY 10044",
  },
  {
    region: "RI",
    name: "Manhattan Park 30",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MP 30-{year}",
    billToCompany: "ROOSEVELT ISLAND ASSOCIATES",
    billToAddress: "30 River Rd, New York, NY 10044",
  },
  {
    region: "RI",
    name: "Manhattan Park 40",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MP 40-{year}",
    billToCompany: "ROOSEVELT ISLAND ASSOCIATES",
    billToAddress: "30 River Rd, New York, NY 10044",
  },

  // ============================================================
  // 8 Spruce
  // ============================================================
  {
    region: "中城",
    name: "8 Spruce St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-8 Spruce St-{year}",
    billToCompany: "",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },

  // ============================================================
  // Stuyvesant Town
  // ============================================================
  {
    region: "Stuyvesant",
    name: "1 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-1 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "2 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-2 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "3 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-3 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "5 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-5 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "7 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-7 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "8 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-8 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "10 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-10 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "12 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-12 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "14 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-14 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "17 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-17 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "18 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-18 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "21 Stuyvesant Oval",
    submissionType: "email",
    invoiceNumberFormat: "Unit-21 Stuyvesant Oval-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "245 Avenue C",
    submissionType: "email",
    invoiceNumberFormat: "Unit-245 Avenue C-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "277 Avenue C",
    submissionType: "email",
    invoiceNumberFormat: "Unit-277 Avenue C-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "301 Avenue C",
    submissionType: "email",
    invoiceNumberFormat: "Unit-301 Avenue C-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "315 Avenue C",
    submissionType: "email",
    invoiceNumberFormat: "Unit-315 Avenue C-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "245 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-245 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "270 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-270 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "272 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-272 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "272 First Ave-Stay Town",
    submissionType: "email",
    invoiceNumberFormat: "Unit-272 First Ave-Stay Town-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "280 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-280 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "284 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-284 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "310 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-310 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "330 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-330 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "346 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-346 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "405 E 14th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-405 E 14th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "435 E 14th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-435 E 14th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "447 E 14th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-447 E 14th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "505 E 14th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-505 E 14th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "521 E 14th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-521 E 14th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "535 E 14th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-535 E 14th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "605 E 14th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-605 E 14th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "625 E 14th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-625 E 14th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "635 E 14th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-635 E 14th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "655 E 14th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-655 E 14th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "420 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-420 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "440 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-440 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "450 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-450 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "510 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-510 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "522 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-522 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "526 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-526 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "610 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-610 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "622 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-622 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Stuyvesant",
    name: "626 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-626 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },

  // ============================================================
  // Peter Cooper Village
  // ============================================================
  {
    region: "Peter Cooper",
    name: "2 Peter Cooper Road",
    submissionType: "email",
    invoiceNumberFormat: "Unit-2 Peter Cooper Road-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "3 Peter Cooper Road",
    submissionType: "email",
    invoiceNumberFormat: "Unit-3 Peter Cooper Road-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "4 Peter Cooper Road",
    submissionType: "email",
    invoiceNumberFormat: "Unit-4 Peter Cooper Road-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "5 Peter Cooper Road",
    submissionType: "email",
    invoiceNumberFormat: "Unit-5 Peter Cooper Road-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "6 Peter Cooper Road",
    submissionType: "email",
    invoiceNumberFormat: "Unit-6 Peter Cooper Road-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "7 Peter Cooper Road",
    submissionType: "email",
    invoiceNumberFormat: "Unit-7 Peter Cooper Road-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "8 Peter Cooper Road",
    submissionType: "email",
    invoiceNumberFormat: "Unit-8 Peter Cooper Road-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "350 1st Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-350 1st Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "360 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-360 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "370 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-370 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "390 First Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-390 First Ave-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "420 E 23rd St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-420 E 23rd St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "440 E 23rd St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-440 E 23rd St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "441 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-441 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "510 E 20th St (Peter Cooper)",
    submissionType: "email",
    invoiceNumberFormat: "Unit-510 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "511 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-511 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "530 E 23rd St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-530 E 23rd St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "535 E 23rd St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-535 E 23rd St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "541 E 29th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-541 E 29th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },
  {
    region: "Peter Cooper",
    name: "601 E 20th St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-601 E 20th St-{year}",
    billToCompany: "BPP ST Owner LLC",
    billToAddress: "276 First Ave Loop, New York, NY 10009",
  },

  // ============================================================
  // Bronx
  // ============================================================
  {
    region: "Bronx",
    name: "The Motto",
    managementCompany: "K&R Realty",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MOTTO-{year}",
    billToCompany: "E 135 and 3rd Ave Owner LLC",
    billToAddress: "2435 Third Ave, Bronx, NY 10451",
  },
  {
    region: "Bronx",
    name: "Maven",
    managementCompany: "Bozzuto",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MAVEN-{year}",
    billToCompany: "RXR 2414 Third LLC",
    billToAddress: "2413 Third Ave, Bronx, NY 10451",
  },

  // ============================================================
  // LIC (Long Island City)
  // ============================================================
  {
    region: "LIC",
    name: "47-05 Center Boulevard",
    submissionType: "email",
    invoiceNumberFormat: "Unit-4705 CTR BLVD-{year}",
    billToCompany: "47-05 Center SPE LLC",
    billToAddress: "4705 Center Blvd, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "The Bold",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE BOLD-{year}",
    billToCompany: "2701 Property Owner LLC",
    billToAddress: "27-01 Jackson Ave, Long Island City, NY 11101",
  },
  {
    region: "LIC",
    name: "27 on 27th",
    submissionType: "email",
    invoiceNumberFormat: "Unit-27 ON 27-{year}",
    billToCompany: "",
    billToAddress: "27-03 42nd Rd, Long Island City, NY 11101",
  },
  {
    region: "LIC",
    name: "45-57 Davis St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-4507 DAVIS-{year}",
    billToCompany: "",
    billToAddress: "45-57 Davis St, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "8 Court Square",
    submissionType: "email",
    invoiceNumberFormat: "Unit-8 COURT SQ-{year}",
    billToCompany: "8 Court Square",
    billToAddress: "2705 Thomson Ave, Long Island City, NY 11101",
  },
  {
    region: "LIC",
    name: "ALTA LIC",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ALTA-{year}",
    billToCompany: "ALTA LIC LLC",
    billToAddress: "29-22 Northern Blvd, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "ARC",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ARC-{year}",
    billToCompany: "30-02 Associates LLC",
    billToAddress: "30-02 29th Ave, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "The Astor LIC",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ASTOR-{year}",
    billToCompany: "STEINWAY STREET INVESTORS LLC",
    billToAddress: "575 5th Ave, 9th Fl., New York, NY 10017",
  },
  {
    region: "LIC",
    name: "Astoria West",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ASTORIA WEST-{year}",
    billToCompany: "ASTORIA WEST LLC",
    billToAddress: "11-12 30th Drive Astoria, New York, NY 11102",
  },
  {
    region: "LIC",
    name: "Jasper",
    submissionType: "email",
    invoiceNumberFormat: "Unit-JASPER-{year}",
    billToCompany: "50th & 5th LLC, LLC",
    billToAddress: "2-33 50th Ave, Long Island City, NY 11101",
  },
  {
    region: "LIC",
    name: "Terra",
    submissionType: "email",
    invoiceNumberFormat: "Unit-TERRA-{year}",
    billToCompany: "Davis Street Development LLC",
    billToAddress: "60 Cuttermill Road, Suite 405, Great Neck, NY 11021",
  },
  {
    region: "LIC",
    name: "LINK",
    submissionType: "email",
    invoiceNumberFormat: "Unit-LINK-{year}",
    billToCompany: "Queens Plaza North New York LLC",
    billToAddress: "41-46 27th street, Long Island City, NY 11101",
  },
  {
    region: "LIC",
    name: "Avalon Riverview",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AVA RIVER-{year}",
    billToCompany: "Avalon Riverview",
    billToAddress: "4-75 48th Ave, Long Island City, NY 11109",
  },
  {
    region: "LIC",
    name: "The Italic",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ITALIC-{year}",
    billToCompany: "Italic Realty LLC",
    billToAddress: "26-38 Jackson Ave, Long Island City, NY 11101",
  },
  {
    region: "LIC",
    name: "Dutch House",
    submissionType: "email",
    invoiceNumberFormat: "Unit-DUTCH HOUSE-{year}",
    billToCompany: "Dutch House Apartment",
    billToAddress: "37-09 30th St, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "Linc",
    submissionType: "email",
    invoiceNumberFormat: "Unit-LINC-{year}",
    billToCompany: "LINC LIC LLC",
    billToAddress: "43-10 Crescent St, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "Eagle Lofts",
    submissionType: "email",
    invoiceNumberFormat: "Unit-EAGLE LOFTS-{year}",
    billToCompany: "43-22 Queens Street LLC",
    billToAddress: "43-22 Queens St, Long Island City, NY 11101",
  },
  {
    region: "LIC",
    name: "Eagle Lofts 2",
    submissionType: "email",
    invoiceNumberFormat: "Unit-EAGLE 2-{year}",
    billToCompany: "27-34 Jackson L.L.C.",
    billToAddress: "43-10 Queens Street AKA 43-14 Queens Street Long IslandCity, NY 11101",
  },
  {
    region: "LIC",
    name: "The Cove",
    submissionType: "email",
    invoiceNumberFormat: "Unit-COVE-{year}",
    billToCompany: "43-12 HUNTER LLC",
    billToAddress: "43-12 Hunter St, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "Hayden",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HAYDEN-{year}",
    billToCompany: "Hayden LIC Apartments",
    billToAddress: "43-25 Hunter St, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "Jackson Park 1",
    submissionType: "email",
    invoiceNumberFormat: "Unit-JP 1-{year}",
    billToCompany: "LIC DEVELOPMENT OWNER LP",
    billToAddress: "28-40 Jackson Ave, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "Jackson Park 2",
    submissionType: "email",
    invoiceNumberFormat: "Unit-JP 2-{year}",
    billToCompany: "LIC DEVELOPMENT OWNER LP",
    billToAddress: "26-30 Jackson Ave, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "Jackson Park 3",
    submissionType: "email",
    invoiceNumberFormat: "Unit-JP 3-{year}",
    billToCompany: "LIC DEVELOPMENT OWNER LP",
    billToAddress: "28-10 Jackson Ave, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "Gotham Point",
    submissionType: "email",
    invoiceNumberFormat: "Unit-GOTHAM POINT-{year}",
    billToCompany: "GO HPS LLC",
    billToAddress: "432 Park Avenue South, 2nd Floor, New York, NY 10016",
  },
  {
    region: "LIC",
    name: "One LIC",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ONE LIC-{year}",
    billToCompany: "One LIC",
    billToAddress: "42-12 27th St, Long Island City, NY 11101",
  },
  {
    region: "LIC",
    name: "Rise LIC",
    submissionType: "email",
    invoiceNumberFormat: "Unit-RISE-{year}",
    billToCompany: "LIC OWNER, LLC",
    billToAddress: "29-17 40th Ave., Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "Hunters View Condominium",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HVC-{year}",
    billToCompany: "The Corcoran Group",
    billToAddress: "46-15 11th St, Long Island City, NY 11101",
  },
  {
    region: "LIC",
    name: "Skyline Tower",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SKYLINE TOWER-{year}",
    billToCompany: "Skyline Tower",
    billToAddress: "3 Ct Square W, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "STEEL HAUS",
    submissionType: "email",
    invoiceNumberFormat: "Unit-STEEL HAUS-{year}",
    billToCompany: "27TH STREET PARTNERS LLC",
    billToAddress: "41-52 27th St, Long Island City, NY 11101",
  },
  {
    region: "LIC",
    name: "Sven",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SVEN-{year}",
    billToCompany: "QPP LLC",
    billToAddress: "29-59 Northern Blvd, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "The Forge",
    submissionType: "email",
    invoiceNumberFormat: "Unit-FORGE-{year}",
    billToCompany: "The Forge",
    billToAddress: "44-35 Purves St, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "Tower 28",
    submissionType: "email",
    invoiceNumberFormat: "Unit-TOWER 28-{year}",
    billToCompany: "4212 28th Street LLC",
    billToAddress: "42-12 28th St, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "TRIO",
    submissionType: "email",
    invoiceNumberFormat: "Unit-TRIO-{year}",
    billToCompany: "Thomson Development LLC",
    billToAddress: "27-19 Thomson Ave, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "LUCENT33",
    submissionType: "email",
    invoiceNumberFormat: "Unit-LUCENT33-{year}",
    billToCompany: "33rd Street Ventures LLC",
    billToAddress: "37-34 33rd St, Queens, NY 11101",
  },
  {
    region: "LIC",
    name: "1 GPS",
    submissionType: "email",
    invoiceNumberFormat: "Unit-1GPS-{year}",
    billToCompany: "One QPS Owner LLC Stonehenge NYC",
    billToAddress: "1675 Broadway 21st Fl, New York, NY 10019",
  },

  // ============================================================
  // Queens
  // ============================================================
  {
    region: "Queens",
    name: "The Elm West",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ELM WEST-{year}",
    billToCompany: "85-15 Queens Blvd, Realty, LLC",
  },
  {
    region: "Queens",
    name: "The Elm East",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ELM EAST-{year}",
    billToCompany: "86#163 Realty, LLC",
    billToAddress: "136-18 39th Ave 12th Fl, Flushing NY 11354",
  },
  {
    region: "Queens",
    name: "The Yellowstone Forest House",
    submissionType: "email",
    invoiceNumberFormat: "Unit-YELLOWSTONE-{year}",
    billToCompany: "108-02 FOREST HILLS LLC",
    billToAddress: "440 Park Avenue South, 8th Floor, New York, NY 10016",
  },
  {
    region: "Queens",
    name: "VIDA 52",
    submissionType: "email",
    invoiceNumberFormat: "Unit-VIDA 52-{year}",
    billToCompany: "VIDA52 (Woodside)",
    billToAddress: "43-15 52nd St, Queens, NY 11377",
  },
  {
    region: "Queens",
    name: "SOLA Woodside",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SOLA-{year}",
    billToCompany: "QB property LLC",
    billToAddress: "72-01 Queens Blvd, Woodside, NY 11377",
  },
  {
    region: "Queens",
    name: "Parker Tower",
    submissionType: "email",
    invoiceNumberFormat: "Unit-10425-{year}",
    billToCompany: "Parker Tower Property, LLC",
    billToAddress: "10420 Queens Blvd, Suit 1C, Forest Hills, NY 11375",
  },

  // ============================================================
  // BK (Brooklyn)
  // ============================================================
  {
    region: "BK",
    name: "Brooklyn Point",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BK POINT-{year}",
    billToCompany: "138 Willoughby LLC",
    billToAddress: "1 City Pt, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "City Tower",
    submissionType: "email",
    invoiceNumberFormat: "Unit-CITY TOWER-{year}",
    billToCompany: "City Tower",
    billToAddress: "10 City Pt, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "AVA DoBro",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AVA DOBRO-{year}",
    billToCompany: "AVA DoBro",
    billToAddress: "100 Willoughby St, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "The Brooklyner",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BROOKLYNER-{year}",
    billToCompany: "The Brooklyner Apartments",
    billToAddress: "111 Lawrence St, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "The Amberly",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AMBERLY-{year}",
    billToCompany: "The Amberly Apartments",
    billToAddress: "120 Nassau St, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "PLG",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PLG-{year}",
    billToCompany: "The Moinian Group",
    billToAddress: "123 Linden Blvd, Brooklyn, NY 11226",
  },
  {
    region: "BK",
    name: "180 Franklin Avenue",
    submissionType: "email",
    invoiceNumberFormat: "Unit-180 FRANKLIN-{year}",
    billToCompany: "MD CBD 180 Franklin LLC",
    billToAddress: "180 Franklin Ave, Brooklyn, NY 11205",
  },
  {
    region: "BK",
    name: "196 Willoughby St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-196 WILLOUGHBY-{year}",
    billToCompany: "RXR 196 Willoughby Owner LLC",
    billToAddress: "196 Willoughby St, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "Avalon Willoughby Square",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AVA WILLOUGHBY-{year}",
    billToCompany: "Avalon Willoughby",
  },
  {
    region: "BK",
    name: "Avalon Fort Greene",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AVA FORT-{year}",
    billToCompany: "AVA Fort Greene",
  },
  {
    region: "BK",
    name: "325 Lafayette",
    submissionType: "email",
    invoiceNumberFormat: "Unit-325 LAFAYETTE-{year}",
    billToCompany: "325 Lafayette Associates LLC",
    billToAddress: "325 Lafayette Ave, Brooklyn, NY 11238",
  },
  {
    region: "BK",
    name: "Hub",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HUB-{year}",
    billToCompany: "HUB BK LLC",
    billToAddress: "333 Schermerhorn St, Brooklyn, NY 11217",
  },
  {
    region: "BK",
    name: "Prosper Brooklyn",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PROSPER BK-{year}",
    billToCompany: "EMP Atlantic Property Owner LP",
    billToAddress: "670 Myrtle Avenue, Suite 575, Brooklyn, NY 11205",
  },
  {
    region: "BK",
    name: "The Everly",
    submissionType: "email",
    invoiceNumberFormat: "Unit-EVERLY-{year}",
    billToCompany: "Rockrose",
    billToAddress: "180 Ashland Pl, Brooklyn, NY 11217",
  },
  {
    region: "BK",
    name: "The Rocklyn",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ROCKLYN-{year}",
    billToCompany: "Fulton Realty Development LLC",
    billToAddress: "20 Rockwell Pl, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "Hoyt and Horn",
    submissionType: "email",
    invoiceNumberFormat: "Unit-HOYT AND HORN-{year}",
    billToCompany: "Hoyt and Horn",
    billToAddress: "45 Hoyt St, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "The Paxton",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PAXTON-{year}",
    billToCompany: "The Paxton",
    billToAddress: "540 Fulton St, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "Loden",
    submissionType: "email",
    invoiceNumberFormat: "Unit-LODEN-{year}",
    billToCompany: "CP VI Crown Owners LLC",
    billToAddress: "54 Crown Street, Brooklyn, NY 11225",
  },
  {
    region: "BK",
    name: "Society Brooklyn at Degraw",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SOCIETY BK-{year}",
    billToCompany: "Bayside Gowanus Owner LLC",
    billToAddress: "500 Degraw St, Brooklyn, NY 11217",
  },
  {
    region: "BK",
    name: "The Brooklyn Tower",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BK TOWER-{year}",
    billToCompany: "9 Dekalb Fee Owner LLC",
    billToAddress: "104 Fifth Avenue, 9th Floor, NY",
  },
  {
    region: "BK",
    name: "Staten Island Urby Apartments",
    submissionType: "email",
    invoiceNumberFormat: "Unit-STATEB ISL URBY-{year}",
    billToCompany: "Homeport I LLC",
    billToAddress: "50 Washington Street, Hoboken, NJ",
  },
  {
    region: "BK",
    name: "505 State St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-505 STATE-{year}",
    billToCompany: "110 Flatbush Avenue LLC",
    billToAddress: "505 State St, Brooklyn, NY 11217",
  },
  {
    region: "BK",
    name: "The Highland BK",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE HIGHLAND-{year}",
    billToCompany: "Empire State Dairy LLC",
    billToAddress: "2840 Atlantic Ave, Brooklyn, NY 11207",
  },
  {
    region: "BK",
    name: "22 Chapel",
    submissionType: "email",
    invoiceNumberFormat: "Unit-22 CHAPEL-{year}",
    billToCompany: "22 CHAPEL MASTER TENANT LLC",
    billToAddress: "22 Chapel St, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "Parish House",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PARISH HOUSE-{year}",
    billToCompany: "230 GLASSON DEVELOPMENT LLC",
    billToAddress: "249 Willoughby Ave, Brooklyn, NY 11205",
  },
  {
    region: "BK",
    name: "Bklyn Gold 257",
    submissionType: "email",
    invoiceNumberFormat: "Unit-257 BK GOLD-{year}",
    billToCompany: "Brooklyn Gold SPE LLC",
    billToAddress: "257 Gold St, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "BKLYN AIR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BK AIR-{year}",
    billToCompany: "Brooklyn Princess LLC",
    billToAddress: "309 Gold St, Brooklyn, NY 11201",
  },
  {
    region: "BK",
    name: "The Guild",
    submissionType: "email",
    invoiceNumberFormat: "Unit-GUILD-{year}",
    billToCompany: "Longview Owner LLC",
    billToAddress: "310 Livingston Street, Brooklyn, NY 11217",
  },

  // ============================================================
  // NJ
  // ============================================================
  {
    region: "NJ",
    name: "65 Bay St",
    submissionType: "email",
    invoiceNumberFormat: "Unit-65 BAY-{year}",
    billToCompany: "West Management LLC",
  },
  {
    region: "NJ",
    name: "Cobalt Lofts",
    managementCompany: "Bozzuto",
    submissionType: "email",
    invoiceNumberFormat: "Unit-COBALT LOFTS-{year}",
    billToCompany: "Cobalt Lofts",
  },
  {
    region: "NJ",
    name: "The Wyldes",
    managementCompany: "Bozzuto",
    submissionType: "email",
    invoiceNumberFormat: "Unit-WYLDES-{year}",
    billToCompany: "The Wyldes",
  },
  {
    region: "NJ",
    name: "Steel Works",
    managementCompany: "Bozzuto",
    submissionType: "email",
    invoiceNumberFormat: "Unit-STEEL WORKS-{year}",
    billToCompany: "Steel Works",
  },
  {
    region: "NJ",
    name: "The Modern - 100",
    managementCompany: "Bozzuto",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MODERN 100-{year}",
    billToCompany: "The Modern 100",
  },
  {
    region: "NJ",
    name: "The Modern - 800",
    managementCompany: "Bozzuto",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MODERN 800-{year}",
    billToCompany: "The Modern 800",
  },
  {
    region: "NJ",
    name: "The Declan",
    managementCompany: "Bozzuto",
    submissionType: "email",
    invoiceNumberFormat: "Unit-DECLAN-{year}",
    billToCompany: "The Declan",
  },

  // === NPR 管理 ===
  {
    region: "NJ",
    name: "Aquablu at Newport",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AQUABLU-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "Atlantic at Newport",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ATLANTIC-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "East Hampton",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-EASTHAMPTON-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "Ellipse",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ELLIPSE-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "Embankment House",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-EMBANKMENT HOUSE-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "Laguna at Newport",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-LAGUNA-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "Pacific at Newport",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PACIFIC-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "Parkside East",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PARKSIDE EAST-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "Parkside West",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-PARKSIDE WEST-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "Revetment House",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-REVETMENT HOUSE-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "Riverside at Newport",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-RIVERSIDE-{year}",
    billToCompany: "Newport Rentals",
  },
  {
    region: "NJ",
    name: "Southampton",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SOUTHAMPTON-{year}",
    billToCompany: "Newport Rentals",
    billToAddress: "121 Town Square Pl, Jersey City, NJ 07310",
  },
  {
    region: "NJ",
    name: "The Beach",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BEACH-{year}",
    billToCompany: "Newport Rentals",
    billToAddress: "121 Town Square Pl, Jersey City, NJ 07310",
  },
  {
    region: "NJ",
    name: "Waterside Square North at Newport",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-WATERSIDE SQ N-{year}",
    billToCompany: "Newport Rentals",
    billToAddress: "121 Town Square Pl, Jersey City, NJ 07310",
  },
  {
    region: "NJ",
    name: "Waterside Square South at Newport",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-WATERSIDE SQ S-{year}",
    billToCompany: "Newport Rentals",
    billToAddress: "121 Town Square Pl, Jersey City, NJ 07310",
  },
  {
    region: "NJ",
    name: "Brine at Newport",
    managementCompany: "NPR",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BRINE-{year}",
    billToCompany: "Wave Building LLC",
    billToAddress: "30 Park Lane North, Jersey City, NJ 07310",
  },

  // === NJ — Other ===
  {
    region: "NJ",
    name: "Grove Pointe Apartments",
    submissionType: "email",
    invoiceNumberFormat: "Unit-GROVE POINTE-{year}",
    billToCompany: "Grove Pointe Urban Renewal LLC",
    billToAddress: "100 Christopher Columbus Dr, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "Journal Squared 1",
    submissionType: "email",
    invoiceNumberFormat: "Unit-JSQ 1-{year}",
    billToCompany: "Journal Squared Urban Renewal LLC",
    billToAddress: "615 Pavonia Ave, Jersey City, NJ 07306",
  },
  {
    region: "NJ",
    name: "Journal Squared 2",
    submissionType: "email",
    invoiceNumberFormat: "Unit-JSQ 2-{year}",
    billToCompany: "Journal Squared Urban Renewal Assoc LLC",
    billToAddress: "605 Pavonia Ave, Jersey City, NJ 07306",
  },
  {
    region: "NJ",
    name: "Journal Squared 3",
    submissionType: "email",
    invoiceNumberFormat: "Unit-JSQ 3-{year}",
    billToCompany: "Journal Squared III Urban Renewal LLC",
    billToAddress: "595 Pavonia Ave, Jersey City, NJ 07306",
  },
  {
    region: "NJ",
    name: "Bay 151-Building 1",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BAY 151-{year}",
    billToCompany: "151 Centre Street Urban Renewal LLC",
    billToAddress: "151 E Centre St Suite A, Bayonne, NJ 07002",
  },
  {
    region: "NJ",
    name: "Bay 151-Building 2",
    submissionType: "email",
    invoiceNumberFormat: "Unit-275 Chosin-{year}",
    billToCompany: "275 Chosin Few Way Urban Renewal LLC",
    billToAddress: "275 Chosin Few Wy, Bayonne, NJ 07002",
  },
  {
    region: "NJ",
    name: "Bay 151-Building 3",
    submissionType: "email",
    invoiceNumberFormat: "Unit-225 Chosin-{year}",
    billToCompany: "225 Chosin Few Way Urban Renewal LLC",
    billToAddress: "225 Chosin Few Wy, Bayonne, NJ 07002",
  },
  {
    region: "NJ",
    name: "FIAT House",
    submissionType: "email",
    invoiceNumberFormat: "Unit-FIAT HOUSE-{year}",
    billToCompany: "2100 North Central Rd FL LLC",
    billToAddress: "2100 North Central Rd, Fort Lee, NJ 07024",
  },
  {
    region: "NJ",
    name: "Jersey City Urby",
    submissionType: "email",
    invoiceNumberFormat: "Unit-JC URBY-{year}",
    billToCompany: "Jersey City Urby",
    billToAddress: "200 Greene St, Jersey City, NJ",
  },
  {
    region: "NJ",
    name: "Iconiq 777",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ICONIQ 777-{year}",
    billToCompany: "777 McCarter urban renewal LLC",
    billToAddress: "120 Albany Street, 8th Floor, NJ",
  },
  {
    region: "NJ",
    name: "Dey & Bergen",
    submissionType: "email",
    invoiceNumberFormat: "Unit-DEY BERGEN-{year}",
    billToCompany: "Dey and Bergen Partners Urban",
    billToAddress: "1 Bergen St, Harrison, NJ 07029",
  },
  {
    region: "NJ",
    name: "Overlook Flats",
    submissionType: "email",
    invoiceNumberFormat: "Unit-OVERLOOK-{year}",
    billToCompany: "Overlook, LLC",
    billToAddress: "110 South Jefferson Rd, Suite",
  },
  {
    region: "NJ",
    name: "Avalon Cove",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AVA COVE-{year}",
    billToCompany: "Avalon Cove",
    billToAddress: "444 Washington Blvd, Jersey City, NJ",
  },
  {
    region: "NJ",
    name: "90 Columbus",
    submissionType: "email",
    invoiceNumberFormat: "Unit-90 COLUMBUS-{year}",
    billToCompany: "90 Columbus by Ironstate, LLC",
    billToAddress: "90 Christopher Columbus Dr, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "The Gotham",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE GOTHAM-{year}",
    billToCompany: "The Gotham",
    billToAddress: "255 Warren St, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "Birch house",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BIRCH HOUSE-{year}",
    billToCompany: "49 Fisk Property Owner LLC",
    billToAddress: "49 Fisk St, Jersey City, NJ 07305",
  },
  {
    region: "NJ",
    name: "BLVD 401",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BLVD 401-{year}",
    billToCompany: "Marbella Tower Urban Renewal Associates, South, L.L.C.",
    billToAddress: "401 Washington Blvd, Jersey City, NJ 07310",
  },
  {
    region: "NJ",
    name: "BLVD 425",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BLVD 425-{year}",
    billToCompany: "Marbella Tower Urban Renewal Associates, L.L.C.",
    billToAddress: "425 Washington Blvd, Jersey City, NJ 07310",
  },
  {
    region: "NJ",
    name: "BLVD 475-N",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BLVD 475-N-{year}",
    billToCompany: "Monaco North Urban Renewal, L.L.C.",
    billToAddress: "475 Washington Blvd, Jersey City, NJ 07310",
  },
  {
    region: "NJ",
    name: "BLVD 475-S",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BLVD 475-S-{year}",
    billToCompany: "Monaco South Urban Renewal, L.L.C.",
    billToAddress: "465 Washington Blvd, Jersey City, NJ 07310",
  },
  {
    region: "NJ",
    name: "55 Orchard JC",
    submissionType: "email",
    invoiceNumberFormat: "Unit-55 Orchard-{year}",
    billToCompany: "Modern Spaces NJ, LLC",
    billToAddress: "295 Newark Ave, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "One Grove",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ONE GROVE-{year}",
    billToCompany: "One Grove Property LLC",
    billToAddress: "215 Grove St, Jersey City, NJ",
  },
  {
    region: "NJ",
    name: "MetroVue",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MetroVue-{year}",
    billToCompany: "161 Van Wagenen LLC",
    billToAddress: "30 Hudson St. 30th Fl, suite 3",
  },
  {
    region: "NJ",
    name: "3 Acres",
    submissionType: "email",
    invoiceNumberFormat: "Unit-3 ACRES-{year}",
    billToCompany: "400 Claremont LLC",
    billToAddress: "400 Claremont Ave, Jersey City",
  },
  {
    region: "NJ",
    name: "330 Angelo Cifelli",
    submissionType: "email",
    invoiceNumberFormat: "Unit-330 ANGELO CIFELLI-{year}",
    billToCompany: "Harrison Building 3 Urban Renewal",
    billToAddress: "50 Washington street, Hoboken",
  },
  {
    region: "NJ",
    name: "The Eddy, Harrison",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE EDDY-{year}",
    billToCompany: "Benjamin Harrison Urban Renewal",
    billToAddress: "50 Washington street, Hoboken",
  },
  {
    region: "NJ",
    name: "Newark Urby",
    submissionType: "email",
    invoiceNumberFormat: "Unit-NWK URBY-{year}",
    billToCompany: "155 Washington Street Urban Renewal LLC",
    billToAddress: "155 Washington St, Newark, NJ 07102",
  },
  {
    region: "NJ",
    name: "425 Summit Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-425 SUMMIT-{year}",
    billToCompany: "Four Twenty Five Summit",
    billToAddress: "425 Summit Ave, Jersey City, NJ 07306",
  },
  {
    region: "NJ",
    name: "Journal Square URBY",
    submissionType: "email",
    invoiceNumberFormat: "Unit-JSQ URBY-{year}",
    billToCompany: "Journal Square Urby Apartments",
    billToAddress: "532 Summit Ave, Jersey City, NJ 07306",
  },
  {
    region: "NJ",
    name: "626 Newark Ave",
    submissionType: "email",
    invoiceNumberFormat: "Unit-626 NEWARK-{year}",
    billToCompany: "CMPND",
    billToAddress: "632 Newark Ave, Jersey City, NJ 07306",
  },
  {
    region: "NJ",
    name: "Le Leo",
    submissionType: "email",
    invoiceNumberFormat: "Unit-LE LEO-{year}",
    billToCompany: "Le Leo",
    billToAddress: "244 St Pauls Ave, Jersey City, NJ 07306",
  },
  {
    region: "NJ",
    name: "9 Homestead",
    submissionType: "email",
    invoiceNumberFormat: "Unit-9 HOMESTEAD-{year}",
    billToCompany: "9 Homestead",
    billToAddress: "9 Homestead Pl, Jersey City, NJ 07306",
  },
  {
    region: "NJ",
    name: "55 Jordan",
    submissionType: "email",
    invoiceNumberFormat: "Unit-55 JORDAN-{year}",
    billToCompany: "Modern Spaces NJ, LLC",
    billToAddress: "55 Jordan Ave, Jersey City, NJ 07306",
  },
  {
    region: "NJ",
    name: "26 Van Reipen",
    submissionType: "email",
    invoiceNumberFormat: "Unit-26 VR-{year}",
    billToCompany: "Namdar Group",
    billToAddress: "26 Van Reipen Ave, Jersey City, NJ 07306",
  },
  {
    region: "NJ",
    name: "28 Cottage",
    submissionType: "email",
    invoiceNumberFormat: "Unit-28 COTTAGE-{year}",
    billToCompany: "28 Cottage",
    billToAddress: "28 Cottage St, New Jersey, NJ 07306",
  },
  {
    region: "NJ",
    name: "Xchange at Secaucus Junction",
    submissionType: "email",
    invoiceNumberFormat: "Unit-Xchange-{year}",
    billToCompany: "South Riverside Station LLC",
    billToAddress: "4000 Riverside Station Blvd, Secaucus",
  },
  {
    region: "NJ",
    name: "The Edge at Raritan Heights",
    submissionType: "email",
    invoiceNumberFormat: "Unit-EDGE at RH-{year}",
    billToCompany: "Raritan Heights Phase III LLC",
    billToAddress: "11 US-1, New Brunswick, NJ 08901",
  },
  {
    region: "NJ",
    name: "The Harper at Harmon Meadow",
    submissionType: "email",
    invoiceNumberFormat: "Unit-The Harper-{year}",
    billToCompany: "The Harper at Harmon Meadow",
    billToAddress: "100 Park Plaza Dr, Secaucus, NJ",
  },
  {
    region: "NJ",
    name: "RVR at Xchange",
    submissionType: "email",
    invoiceNumberFormat: "Unit-RVR-{year}",
    billToCompany: "Middlesex Management",
    billToAddress: "90 Woodbridge Center Dr, Woodbridge",
  },
  {
    region: "NJ",
    name: "Ivy & Green",
    submissionType: "email",
    invoiceNumberFormat: "Unit-Ivy & Green-{year}",
    billToCompany: "Ivy & Green c/o RHO Residential",
    billToAddress: "1 Park Avenue, NJ",
  },
  {
    region: "NJ",
    name: "The Grand",
    managementCompany: "Greystar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE GRAND-{year}",
    billToCompany: "The Grand at Broadway Station",
    billToAddress: "140 Manhattan Ave, Union City, NJ",
  },
  {
    region: "NJ",
    name: "Maxwell DTBK",
    submissionType: "email",
    invoiceNumberFormat: "Unit-MAXWELL-{year}",
    billToCompany: "Maxwell DTBK LLC",
    billToAddress: "220 Avenue A, Bayonne, NJ 07002",
  },
  {
    region: "NJ",
    name: "Sable Jersey City Apartments",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SABLE-{year}",
    billToCompany: "Sable Jersey City Apartments",
    billToAddress: "501 Tonnelle Ave, Jersey City, NJ 07307",
  },
  {
    region: "NJ",
    name: "The Breton I",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BRETON I-{year}",
    billToCompany: "The Breton I",
    billToAddress: "200 Breton Way, Glen Rock, NJ",
    specialNotes: "Invoice邮件必须包含 Invoice文件 和 broker referral form，两个文件内信息必须一致",
  },
  {
    region: "NJ",
    name: "The Breton II",
    submissionType: "email",
    invoiceNumberFormat: "Unit-BRETON II-{year}",
    billToCompany: "The Breton II",
    billToAddress: "200 Breton Way, Glen Rock, NJ",
    specialNotes: "Invoice邮件必须包含 Invoice文件 和 broker referral form，两个文件内信息必须一致",
  },
  {
    region: "NJ",
    name: "179 Academy Street",
    submissionType: "email",
    invoiceNumberFormat: "Unit-179 ACADEMY-{year}",
    billToCompany: "179 Academy Street",
    billToAddress: "179 Academy St, Jersey City, NJ",
  },

  // === NJ — Additional buildings from screenshots ===
  {
    region: "NJ",
    name: "Vantage",
    managementCompany: "Bozzuto",
    submissionType: "email",
    submissionNotes: "bozzuto, 发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-VANTAGE-{year}",
    billToCompany: "Vantage Collection",
    billToAddress: "33 Park View Ave, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "18 Park View Avenue",
    managementCompany: "KRE",
    submissionType: "email",
    submissionNotes: "kre, 发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-18 PARK-{year}",
    billToCompany: "Grand Link I Urban Renewal LLC",
    billToAddress: "16 Park View Ave, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "225 Grand",
    managementCompany: "KRE",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-225 GRAND-{year}",
    billToCompany: "225 Grand",
    billToAddress: "225 Grand St, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "235 Grand",
    managementCompany: "KRE",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-235 GRAND-{year}",
    billToCompany: "Grand Link II, LLC",
    billToAddress: "235 Grand Street, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "351 Marin",
    managementCompany: "KRE",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-351 MARIN-{year}",
    billToCompany: "351 Marin LLC",
    billToAddress: "351 Marin Blvd, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "485 Marin Blvd",
    managementCompany: "KRE",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-485 MARIN-{year}",
    billToCompany: "485 Marin Blvd",
    billToAddress: "485 Marin Blvd, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "The Hendrix",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-HENDRIX-{year}",
    billToCompany: "184 Morgan Street Fee Owners L.P.",
    billToAddress: "180 Morgan St, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "The Morgan at Provost Square",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-MORGAN PS-{year}",
    billToCompany: "The Morgan at Provost Square",
    billToAddress: "160 Morgan St, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "The One NJ",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-THE ONE-{year}",
    billToCompany: "BLDG Management Inc Co",
    billToAddress: "110 First Street, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "VYV",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-VYV-{year}",
    billToCompany: "VYV",
    billToAddress: "474 Warren St, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "Haus25",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-HAUS25-{year}",
    billToCompany: "Haus 25",
    billToAddress: "25 Christopher Columbus Dr, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "50 Columbus",
    managementCompany: "Ironstate",
    submissionType: "email",
    submissionNotes: "ironstate, 发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-50 COLUMBUS-{year}",
    billToCompany: "50 Columbus by Ironstate, LLC",
    billToAddress: "50 Christopher Columbus Dr, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "70 Columbus",
    managementCompany: "Ironstate",
    submissionType: "email",
    submissionNotes: "ironstate, 发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-70 COLUMBUS-{year}",
    billToCompany: "70 Columbus by Ironstate, LLC",
    billToAddress: "70 Christopher Columbus Dr, Jersey City, NJ 07302",
  },
  {
    region: "NJ",
    name: "300 SOMERSET",
    managementCompany: "Ironstate",
    submissionType: "email",
    submissionNotes: "ironstate, 发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-300 SOMERSET-{year}",
    billToCompany: "Harrison Building 1 Urban Renewal LLC",
    billToAddress: "50 Washington street, Hoboken NJ 07030",
  },
  {
    region: "NJ",
    name: "Harrison Yards II",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱 (Harrison Yards 二期楼)",
    invoiceNumberFormat: "Unit-HARRISON YARDS II-{year}",
    billToCompany: "Harrison Yards II",
    billToAddress: "450 Angelo Cifelli Drive, Harrison, NJ 07029",
  },
  {
    region: "NJ",
    name: "7 Seventy House",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-7 SEVENTY HOUSE-{year}",
    billToCompany: "7 Seventy House",
    billToAddress: "770 Jackson Street, Hoboken, NJ 07030",
  },
  {
    region: "NJ",
    name: "The Journal North",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit P-JOURNAL NORTH-{year}",
    billToCompany: "One Journal Square Partners Urban Renewal Company, LLC",
    billToAddress: "30 Columbia Turnpike, 3rd Floor Florham Park, NJ 07932",
  },
  {
    region: "NJ",
    name: "The Journal South",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit S-JOURNAL SOUTH-{year}",
    billToCompany: "One Journal Square Tower South Urban Renewal Company, LLC",
    billToAddress: "30 Columbia Turnpike, 3rd Floor Florham Park, NJ 07932",
  },
  {
    region: "NJ",
    name: "Harrison Urby",
    submissionType: "email",
    submissionNotes: "发大楼同时CC公司邮箱",
    invoiceNumberFormat: "Unit-HARR URBY-{year}",
    billToCompany: "Harrison Urby",
    billToAddress: "200 Angelo Cifelli Dr, Harrison, NJ 07029",
  },

  // ============================================================
  // 外州 Sheet (Out of State)
  // ============================================================
  {
    region: "New Brunswick NJ",
    name: "Renaissance Plaza Square Apartments",
    submissionType: "email",
    invoiceNumberFormat: "Unit-RENAISSANCE-{year}",
    billToCompany: "Renaissance Plaza Square Apartments",
    billToAddress: "1 Richmond St, New Brunswick, NJ 08901",
    isOutOfState: true,
  },
  {
    region: "New Brunswick NJ",
    name: "The Quincy",
    submissionType: "email",
    invoiceNumberFormat: "Unit-THE QUINCY-{year}",
    billToCompany: "The Quincy",
    billToAddress: "120 Neilson Street, New Brunswick, NJ 08901",
    isOutOfState: true,
  },
  {
    region: "Navy Yard, DC",
    name: "28K",
    submissionType: "email",
    invoiceNumberFormat: "Unit-28K-{year}",
    billToCompany: "23 I, LLC",
    billToAddress: "28k K St SE, Washington, DC 20003",
    isOutOfState: true,
  },
  {
    region: "Navy Yard, DC",
    name: "10K",
    managementCompany: "Related Rentals",
    submissionType: "email",
    invoiceNumberFormat: "Unit-10K-{year}",
    billToCompany: "950 South Capitol Owner LLC",
    billToAddress: "10 K St SE, Washington, DC 20003",
    isOutOfState: true,
  },
  {
    region: "Navy Yard, DC",
    name: "DC Crossing",
    managementCompany: "Greystar",
    submissionType: "email",
    invoiceNumberFormat: "Unit-CROSSING DC-{year}",
    billToCompany: "Congressional Square (Owner) LLC",
    billToAddress: "949 First St SE, Washington, DC 20003",
    isOutOfState: true,
  },
  {
    region: "费城",
    name: "2301 JFK",
    submissionType: "email",
    invoiceNumberFormat: "Unit-2301JFK-{year}",
    billToCompany: "MRC- Maxwell Realty Company Inc.",
    billToAddress: "1736 Pine Street, Suite 100, Philadelphia, PA 19103",
    isOutOfState: true,
  },
  {
    region: "费城",
    name: "Avira",
    submissionType: "email",
    invoiceNumberFormat: "Unit-AVIRA-{year}",
    billToCompany: "Avira",
    billToAddress: "3025 John F Kennedy Blvd, Philadelphia, PA 19104",
    isOutOfState: true,
  },
  {
    region: "费城",
    name: "Domus",
    submissionType: "email",
    invoiceNumberFormat: "Unit-DOMUS-{year}",
    billToCompany: "Domus",
    billToAddress: "3411 Chestnut St, Philadelphia, PA 19104",
    isOutOfState: true,
  },
  {
    region: "费城",
    name: "Arrive University City",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ARRIVE-{year}",
    billToCompany: "Arrive University City",
    billToAddress: "3601 Market St, Philadelphia, PA 19104",
    isOutOfState: true,
  },
  {
    region: "费城",
    name: "2400 Chestnut",
    submissionType: "email",
    invoiceNumberFormat: "Unit-2400 CHESTNUT-{year}",
    billToCompany: "2400 Chestnut Associates",
    billToAddress: "2400 Chestnut St, Philadelphia, PA 19103",
    isOutOfState: true,
  },
  {
    region: "费城",
    name: "3737 Chestnut",
    submissionType: "email",
    invoiceNumberFormat: "Unit-3737 CHESTNUT-{year}",
    billToCompany: "Korman 3737 Chestnut",
    billToAddress: "3737 Chestnut St, Philadelphia, PA 19104",
    isOutOfState: true,
  },
  {
    region: "费城",
    name: "Uno on Chestnut",
    submissionType: "email",
    invoiceNumberFormat: "Unit-UNO 4125-{year}",
    billToCompany: "Peakmade property management",
    billToAddress: "4125 Chestnut St, Philadelphia, PA 19104",
    isOutOfState: true,
  },
  {
    region: "费城",
    name: "Solo on Chestnut",
    submissionType: "email",
    invoiceNumberFormat: "Unit-SOLO 4233-{year}",
    billToCompany: "4233 Chestnut LLC",
    billToAddress: "4233 Chestnut St, Philadelphia, PA 19104",
    isOutOfState: true,
  },
  {
    region: "费城",
    name: "LVL West",
    submissionType: "email",
    invoiceNumberFormat: "Unit-LVL WEST-{year}",
    billToCompany: "LVL West",
    billToAddress: "4301 Chestnut St, Philadelphia, PA",
    isOutOfState: true,
  },
  {
    region: "费城",
    name: "The Alcott",
    submissionType: "email",
    invoiceNumberFormat: "Unit-ALCOTT-{year}",
    billToCompany: "Southern Land",
    billToAddress: "416 Spring Garden St, Philadelphia, PA",
    isOutOfState: true,
  },
  {
    region: "芝加哥南部",
    name: "5252 Apartment",
    submissionType: "email",
    invoiceNumberFormat: "Unit-5252 APT-{year}",
    billToCompany: "5252 Apartments",
    billToAddress: "5252 S Cornell Ave, Chicago, IL",
    isOutOfState: true,
  },
  {
    region: "芝加哥南部",
    name: "City Hyde Park",
    submissionType: "email",
    invoiceNumberFormat: "Unit-CITY HYDE PARK-{year}",
    billToCompany: "City Hyde Park Apartments",
    billToAddress: "5105 S Harper Ave, Chicago, IL",
    isOutOfState: true,
  },
];

const defaultSettings = [
  { key: "cc_email", value: "homix@homixny.com" },
  { key: "from_email", value: "invoice@homixny.com" },
  { key: "company_name", value: "Homix Living" },
  { key: "company_address", value: "" },
  { key: "default_year", value: "2026" },
  { key: "payable_to", value: "Homix Living Inc." },
  { key: "tax_id", value: "" },
  { key: "mail_check_address", value: "Homix Living Inc." },
  { key: "ach_bank_name", value: "" },
  { key: "ach_routing_number", value: "" },
  { key: "ach_account_number", value: "" },
  { key: "ach_account_name", value: "" },
];

async function seed() {
  console.log("Creating tables...");

  await client.execute(`
    CREATE TABLE IF NOT EXISTS buildings (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      region TEXT NOT NULL,
      name TEXT NOT NULL,
      management_company TEXT,
      submission_type TEXT NOT NULL DEFAULT 'email',
      submission_notes TEXT,
      invoice_number_format TEXT,
      bill_to_company TEXT,
      bill_to_address TEXT,
      contact_email TEXT,
      special_notes TEXT,
      is_out_of_state INTEGER DEFAULT 0,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await client.execute(`
    CREATE TABLE IF NOT EXISTS invoices (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      building_id INTEGER REFERENCES buildings(id),
      invoice_number TEXT NOT NULL,
      file_name TEXT NOT NULL,
      email_subject TEXT,
      unit TEXT NOT NULL,
      tenant_name TEXT NOT NULL,
      agent_email TEXT,
      agent_name TEXT,
      agent_phone TEXT,
      apartment_address TEXT,
      move_in_date TEXT,
      licensed_company TEXT NOT NULL,
      year INTEGER NOT NULL DEFAULT 2026,
      line_items TEXT,
      total_amount REAL NOT NULL,
      notes TEXT,
      status TEXT NOT NULL DEFAULT 'draft',
      sent_at TEXT,
      pdf_data TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await client.execute(`
    CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    )
  `);

  console.log("Inserting buildings...");
  for (const building of buildingsData) {
    await db.insert(buildings).values(building);
  }
  console.log(`Inserted ${buildingsData.length} buildings.`);

  console.log("Inserting settings...");
  for (const setting of defaultSettings) {
    await db.insert(settings).values(setting).onConflictDoNothing();
  }

  console.log("Seed completed!");
}

seed().catch(console.error);
