import { readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import Stripe from "stripe";
import { commerceProducts } from "../src/lib/commerce/catalog";
import { ensureStripeProductPrice } from "../src/lib/commerce/stripe-products";
import { STRIPE_APP_ID } from "../src/lib/commerce/stripe-app";

function unquote(value: string): string {
  const trimmed = value.trim();
  if (
    (trimmed.startsWith("\"") && trimmed.endsWith("\"")) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

function parseStripeCliConfig(source: string): {
  projectName: string;
  testKey: string;
} {
  let section = "";
  const values = new Map<string, Map<string, string>>();
  values.set("", new Map());

  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const sectionMatch = line.match(/^\[([^\]]+)]$/);
    if (sectionMatch) {
      section = sectionMatch[1]!;
      if (!values.has(section)) values.set(section, new Map());
      continue;
    }
    const separator = line.indexOf("=");
    if (separator < 1) continue;
    values.get(section)!.set(
      line.slice(0, separator).trim(),
      unquote(line.slice(separator + 1)),
    );
  }

  const projectName = values.get("")?.get("project-name") || "default";
  const testKey = values.get(projectName)?.get("test_mode_api_key") || "";
  if (!/^(sk|rk)_test_[A-Za-z0-9_]+$/.test(testKey)) {
    throw new Error(`Stripe CLI profile ${projectName} has no valid test-mode API key.`);
  }
  return { projectName, testKey };
}

function updateEnv(source: string, updates: Record<string, string>): string {
  const pending = new Map(Object.entries(updates));
  const lines = source.split(/\r?\n/).map((line) => {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=/);
    if (!match || !pending.has(match[1]!)) return line;
    const key = match[1]!;
    const value = pending.get(key)!;
    pending.delete(key);
    return `${key}=${value}`;
  });

  while (lines.length && !lines.at(-1)) lines.pop();
  if (pending.size) {
    if (lines.length) lines.push("");
    lines.push("# Stripe test mode (generated by npm run stripe:test:configure)");
    for (const [key, value] of pending) lines.push(`${key}=${value}`);
  }
  return `${lines.join("\n")}\n`;
}

async function main() {
  const configPath = join(homedir(), ".config", "stripe", "config.toml");
  const { projectName, testKey } = parseStripeCliConfig(await readFile(configPath, "utf8"));
  const stripe = new Stripe(testKey);
  const account = await stripe.accounts.retrieveCurrent();
  const prices: Record<string, string> = {};

  for (const product of commerceProducts) {
    prices[product.priceEnvVar] = await ensureStripeProductPrice(stripe, product);
  }

  const portalConfigurations = await stripe.billingPortal.configurations.list({
    active: true,
    limit: 100,
  });
  const portalConfiguration = portalConfigurations.data.find(
    (configuration) => configuration.metadata?.app === STRIPE_APP_ID,
  ) || await stripe.billingPortal.configurations.create({
    name: "Homix Agents",
    default_return_url: "https://agents.homixny.com/pay",
    metadata: { app: STRIPE_APP_ID },
    features: {
      customer_update: { enabled: false },
      invoice_history: { enabled: true },
      payment_method_update: { enabled: true },
      subscription_cancel: {
        enabled: true,
        mode: "at_period_end",
        proration_behavior: "none",
      },
      subscription_update: { enabled: false },
    },
  });

  const envPath = join(process.cwd(), ".env.local");
  let current = "";
  try {
    current = await readFile(envPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }

  const existingSecret = current.match(/^STRIPE_SECRET_KEY=(.*)$/m)?.[1]?.trim();
  if (existingSecret && !existingSecret.startsWith("sk_test_") && !existingSecret.startsWith("rk_test_")) {
    throw new Error("Refusing to replace a non-test STRIPE_SECRET_KEY in .env.local.");
  }

  await writeFile(
    envPath,
    updateEnv(current, {
      STRIPE_SECRET_KEY: testKey,
      ...prices,
      STRIPE_CUSTOMER_PORTAL_CONFIGURATION: portalConfiguration.id,
      STRIPE_AUTOMATIC_TAX: "0",
    }),
    { encoding: "utf8", mode: 0o600 },
  );

  console.log(
    `Configured Stripe test mode for ${account.settings?.dashboard?.display_name || "Stripe account"} (${account.id}).`,
  );
  console.log(`CLI profile: ${projectName}`);
  console.log(`Wrote ${Object.keys(prices).length} Homix Price IDs to .env.local.`);
  console.log(`Billing Portal configuration: ${portalConfiguration.id}`);
  console.log("No API key value was printed; .env.local remains gitignored.");
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
