import assert from "node:assert/strict";
import { Pool } from "pg";
import { LEGACY_AGENT_CLAIMS_DDL } from "../../db/legacy-agent-claims";
import { claimLegacyAgent, manageLegacyInvitation, previewLegacyInvitation, hasReservedLegacyProfile, LegacyClaimError } from "../legacy-agent-claims";
import { createLegacyClaimToken, hashLegacyClaimToken, isLegacyGmail } from "../legacy-agent-claim-token";
import { closeDatabaseConnections } from "@/db";

const url = new URL(process.env.DATABASE_URL || "postgres://invalid/invalid");
assert(["localhost", "127.0.0.1"].includes(url.hostname) && url.pathname === "/homix_legacy_claim_test", "Only the disposable local homix_legacy_claim_test database is accepted");
const pool = new Pool({ connectionString: url.toString(), max: 4 });
let checks = 0;
const check = (value: unknown) => { assert.ok(value); checks++; };
const rejects = async (promise: Promise<unknown>, code: string) => { await assert.rejects(promise, e => e instanceof LegacyClaimError && e.code === code); checks++; };
let seq = 0;
async function fixture(email: string | null, extra = "") {
  const id = `profile-${++seq}`;
  const token = createLegacyClaimToken();
  await pool.query(`INSERT INTO public.agents(id,name,slug,phone,license_number,photo_url,visibility_status,email)
    VALUES($1,$2,$1,'555-0100',$3,'/original.jpg','admin_hidden',$4)`, [id, `Original Name ${seq}`, `TEST-${seq}`, email]);
  await pool.query(`INSERT INTO portal.legacy_agent_claims(public_profile_id,expected_email,allow_email_login,authorized_by,token_hash,token_expires_at)
    VALUES($1,$2,$3,1,$4,NOW()+INTERVAL '7 days')`, [id, email, isLegacyGmail(email), hashLegacyClaimToken(token)]);
  if (extra) await pool.query(`UPDATE portal.legacy_agent_claims SET ${extra} WHERE public_profile_id=$1`, [id]);
  return { id, token, license: `TEST-${seq}` };
}
const signIn = (email: string, token?: string, subject = email) => claimLegacyAgent({ email, token, providerSubject: subject, emailVerified: true }, pool);

async function main() {
  try {
    // This fixture deliberately uses no production data and refuses reuse.
    const existing = await pool.query("SELECT to_regclass('portal.agents') AS table_name");
    assert.equal(existing.rows[0].table_name, null, "Use a fresh disposable database");
    check(await signIn("ordinary@gmail.com") === null);
    await pool.query(`CREATE SCHEMA portal;
      CREATE TABLE portal.agents(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,
        phone TEXT,license_number TEXT,pending_email TEXT,is_admin BOOLEAN DEFAULT FALSE,account_status TEXT DEFAULT 'pending',
        legal_name TEXT,agreement_status TEXT DEFAULT 'not_started',agreement_completed_at TIMESTAMPTZ,payment_status TEXT DEFAULT 'pending',
        onboarding_source TEXT,onboarding_website_sync JSONB,licensed_company_id TEXT,licensed_company TEXT,created_at TIMESTAMPTZ,updated_at TIMESTAMPTZ);
      CREATE TABLE portal.agent_email_addresses(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,agent_id INTEGER REFERENCES portal.agents(id),
        email TEXT,kind TEXT,can_sign_in BOOLEAN,is_primary BOOLEAN,verified_at TIMESTAMPTZ,source TEXT,created_by_agent_id INTEGER);
      CREATE UNIQUE INDEX email_unique ON portal.agent_email_addresses(lower(email));
      CREATE TABLE portal.agent_login_identities(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,agent_id INTEGER REFERENCES portal.agents(id),
        provider TEXT,provider_subject TEXT,email_at_link TEXT,is_primary BOOLEAN,verified_at TIMESTAMPTZ,last_used_at TIMESTAMPTZ,disabled_at TIMESTAMPTZ,source TEXT,UNIQUE(provider,provider_subject));
      CREATE TABLE portal.audit_log(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,actor_email TEXT,action TEXT,entity_type TEXT,entity_id TEXT,summary TEXT,detail TEXT);
      CREATE TABLE public.agents(id TEXT PRIMARY KEY,name TEXT,slug TEXT,phone TEXT,email TEXT,license_number TEXT,photo_url TEXT,visibility_status TEXT,portal_agent_id INTEGER UNIQUE REFERENCES portal.agents(id));
      INSERT INTO portal.agents(name,email,is_admin,account_status) VALUES('Admin','admin@example.test',TRUE,'active');`);
    await pool.query(LEGACY_AGENT_CLAIMS_DDL);
    check((await pool.query("SELECT relrowsecurity FROM pg_class WHERE oid='portal.legacy_agent_claims'::regclass")).rows[0].relrowsecurity);
    await rejects(claimLegacyAgent({ email: "unverified@gmail.com", providerSubject: "x", emailVerified: false }, pool), "UNVERIFIED_EMAIL");
    check(await signIn("unregistered@gmail.com") === null);
    const gmail = await fixture("old@gmail.com");
    const before = (await pool.query("SELECT * FROM public.agents WHERE id=$1", [gmail.id])).rows[0];
    const agentId = await signIn(" OLD@GMAIL.COM "); check(agentId);
    const after = (await pool.query("SELECT * FROM public.agents WHERE id=$1", [gmail.id])).rows[0];
    assert.deepEqual(after, { ...before, portal_agent_id: agentId }); checks++;
    const agent = (await pool.query("SELECT * FROM portal.agents WHERE id=$1", [agentId])).rows[0];
    check(agent.account_status === "active" && agent.agreement_status === "not_started" && agent.agreement_completed_at === null && agent.payment_status === "pending" && agent.legal_name === null);
    check(await signIn("old@gmail.com") === null); // existing login now resolves normally
    check(await hasReservedLegacyProfile(gmail.license, agentId!, pool) === false);
    check(await hasReservedLegacyProfile(gmail.license, 999, pool) === true);
    await rejects(signIn("thief@gmail.com", gmail.token), "ALREADY_CLAIMED");
    const other = await fixture("old@hotmail.com");
    check(await signIn("old@hotmail.com") === null);
    const otherAgent = await signIn("new@example.test", other.token); check(otherAgent);
    check(await signIn("new@example.test", other.token) === otherAgent);
    await rejects(signIn("someone@example.test", other.token), "ALREADY_CLAIMED");
    const different = await fixture("reserved@gmail.com");
    const differentAgent = await signIn("chosen@example.test", different.token); check(differentAgent);
    check(await signIn("reserved@gmail.com") === differentAgent);
    check((await pool.query("SELECT count(*)::int n FROM portal.agent_email_addresses WHERE agent_id=$1", [differentAgent])).rows[0].n === 2);
    await pool.query("UPDATE portal.agent_email_addresses SET can_sign_in=FALSE WHERE email='reserved@gmail.com'");
    await rejects(signIn("reserved@gmail.com"), "IDENTITY_CONFLICT");
    const expired = await fixture(null, "token_expires_at=NOW()-INTERVAL '1 second'");
    check(await previewLegacyInvitation(expired.token, pool) === null);
    await rejects(signIn("expired@gmail.com", expired.token), "INVALID_INVITATION");
    const revoked = await fixture("revoked@gmail.com");
    await manageLegacyInvitation({ publicId: revoked.id, actorId: 1, revoke: true }, pool);
    await rejects(signIn("revoked@gmail.com"), "CLAIM_UNAVAILABLE");
    await rejects(signIn("revoked@gmail.com", revoked.token), "INVALID_INVITATION");
    const rotate = await fixture(null);
    const newToken = await manageLegacyInvitation({ publicId: rotate.id, actorId: 1, revoke: false }, pool); check(newToken);
    check(await previewLegacyInvitation(rotate.token, pool) === null);
    check(await previewLegacyInvitation(newToken!, pool));
    check(await previewLegacyInvitation(newToken!, pool)); // previews do not consume
    await rejects(manageLegacyInvitation({ publicId: rotate.id, actorId: agentId!, revoke: false }, pool), "FORBIDDEN");
    const reserved = await fixture("belongs@gmail.com");
    await rejects(signIn("belongs@gmail.com", rotate.token), "INVALID_INVITATION");
    await rejects(signIn("belongs@gmail.com", newToken!), "IDENTITY_CONFLICT");
    const conflict = await fixture(null);
    await rejects(signIn("old@gmail.com", conflict.token), "IDENTITY_CONFLICT");
    await pool.query("INSERT INTO portal.agents(name,email,license_number) VALUES('Other','conflict@example.test',$1)", [conflict.license]);
    await rejects(signIn("fresh@gmail.com", conflict.token), "LICENSE_CONFLICT");
    const race = await fixture(null);
    const racers = await Promise.allSettled([signIn("race-one@gmail.com", race.token), signIn("race-two@gmail.com", race.token)]);
    check(racers.filter(r => r.status === "fulfilled").length === 1);
    check((await pool.query("SELECT count(*)::int n FROM portal.agents WHERE email LIKE 'race-%'")).rows[0].n === 1);
    const rollback = await fixture(null);
    await pool.query(`CREATE FUNCTION reject_claim_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
      IF NEW.entity_id='${rollback.id}' THEN RAISE EXCEPTION 'synthetic audit failure'; END IF; RETURN NEW; END $$;
      CREATE TRIGGER reject_claim_audit BEFORE INSERT ON portal.audit_log FOR EACH ROW EXECUTE FUNCTION reject_claim_audit();`);
    await assert.rejects(signIn("rollback@gmail.com", rollback.token)); checks++;
    check((await pool.query("SELECT portal_agent_id FROM public.agents WHERE id=$1", [rollback.id])).rows[0].portal_agent_id === null);
    check((await pool.query("SELECT count(*)::int n FROM portal.agents WHERE email='rollback@gmail.com'")).rows[0].n === 0);
    check(await previewLegacyInvitation(rollback.token, pool));
    check(await previewLegacyInvitation(reserved.token, pool));
    console.log(`${checks} legacy claim database checks passed; all data synthetic.`);
  } finally { await pool.end(); await closeDatabaseConnections(); }
}
void main();
