import assert from "node:assert/strict";
import postgres from "postgres";

// Throwaway database on the configured Postgres server — created fresh per
// run, dropped in the finally block, so parallel/no-cleanup runs never bleed
// into each other or into the dev database.
const configuredUrl =
  process.env.DATABASE_URL?.trim() || "postgres://postgres@localhost:5499/homixliving";
const dbName = `homix_vis_${Date.now()}_${Math.random().toString(36).slice(2)}`;
const testUrl = new URL(configuredUrl);
testUrl.pathname = `/${dbName}`;
const adminUrl = new URL(configuredUrl);
adminUrl.pathname = "/postgres";
process.env.DATABASE_URL = testUrl.toString();

const adminClient = postgres(adminUrl.toString(), { prepare: false, max: 1, onnotice: () => {} });
let client: ReturnType<typeof postgres> | null = null;

async function execute(sql: string) {
  if (!client) client = postgres(process.env.DATABASE_URL!, { prepare: false, max: 1, onnotice: () => {} });
  await client.unsafe(sql);
}

async function setup() {
  await adminClient.unsafe(`CREATE DATABASE ${dbName}`);
  await execute("CREATE SCHEMA IF NOT EXISTS portal");
  await execute(`
    CREATE TABLE portal.buildings (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      region TEXT NOT NULL,
      name TEXT NOT NULL
    )
  `);
  await execute(`
    CREATE TABLE portal.teams (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT NOT NULL,
      leader_agent_id INTEGER,
      notes TEXT
    )
  `);
  await execute(`
    CREATE TABLE portal.agents (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      split_pct DOUBLE PRECISION NOT NULL DEFAULT 80,
      team_id INTEGER REFERENCES portal.teams(id) ON DELETE SET NULL,
      is_admin BOOLEAN NOT NULL DEFAULT FALSE,
      account_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (account_status IN ('pending', 'active', 'inactive'))
    )
  `);
  await execute(`
    CREATE TABLE portal.rental_deals (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      building_id INTEGER NOT NULL REFERENCES portal.buildings(id),
      unit TEXT NOT NULL,
      tenant_name TEXT NOT NULL,
      total_commission DOUBLE PRECISION NOT NULL,
      licensed_company TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'active',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
  `);
  await execute(`
    CREATE TABLE portal.rental_deal_agents (
      rental_deal_id INTEGER NOT NULL REFERENCES portal.rental_deals(id) ON DELETE CASCADE,
      agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
      share_pct DOUBLE PRECISION NOT NULL,
      is_primary BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (rental_deal_id, agent_id)
    )
  `);
  await execute(`
    CREATE TABLE portal.sale_deals (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      representation_type TEXT NOT NULL,
      stage TEXT NOT NULL DEFAULT 'pre_contract',
      status TEXT NOT NULL DEFAULT 'active',
      property_address TEXT NOT NULL,
      gross_commission DOUBLE PRECISION NOT NULL DEFAULT 0,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
  `);
  await execute(`
    CREATE TABLE portal.sale_deal_agents (
      sale_deal_id INTEGER NOT NULL REFERENCES portal.sale_deals(id) ON DELETE CASCADE,
      agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE RESTRICT,
      share_pct DOUBLE PRECISION NOT NULL,
      is_primary BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (sale_deal_id, agent_id)
    )
  `);

  await execute("INSERT INTO portal.buildings (id, region, name) VALUES (1, 'NYC', 'Test Building')");
  await execute("INSERT INTO portal.teams (id, name, leader_agent_id) VALUES (1, 'Rental Team', 4)");
  await execute(`
    INSERT INTO portal.agents (id, name, email, split_pct, team_id, is_admin, account_status) VALUES
      (1, 'Participant', 'participant@example.com', 70, NULL, FALSE, 'active'),
      (2, 'Outsider', 'outsider@example.com', 70, NULL, FALSE, 'active'),
      (3, 'Team Member', 'member@example.com', 70, 1, FALSE, 'active'),
      (4, 'Team Leader', 'leader@example.com', 70, NULL, FALSE, 'active'),
      (5, 'Inactive Participant', 'inactive@example.com', 70, NULL, FALSE, 'inactive')
  `);
  await execute(`
    INSERT INTO portal.rental_deals (id, building_id, unit, tenant_name, total_commission, licensed_company, status) VALUES
      (101, 1, '1A', 'Self Deal', 5000, 'Homix Living Inc.', 'active'),
      (102, 1, '2B', 'Team Deal', 6000, 'Homix Living Inc.', 'active'),
      (103, 1, '3C', 'Inactive Deal', 7000, 'Homix Living Inc.', 'active')
  `);
  await execute(`
    INSERT INTO portal.rental_deal_agents (rental_deal_id, agent_id, share_pct, is_primary) VALUES
      (101, 1, 100, TRUE),
      (102, 3, 100, TRUE),
      (103, 5, 100, TRUE)
  `);
  await execute(`
    INSERT INTO portal.sale_deals (id, representation_type, stage, status, property_address, gross_commission) VALUES
      (201, 'buyer_rep', 'under_contract', 'active', '1 Sale St', 50000),
      (202, 'seller_rep', 'under_contract', 'active', '2 Sale St', 60000),
      (203, 'buyer_rep', 'under_contract', 'active', '3 Sale St', 70000)
  `);
  await execute(`
    INSERT INTO portal.sale_deal_agents (sale_deal_id, agent_id, share_pct, is_primary) VALUES
      (201, 1, 100, TRUE),
      (202, 3, 100, TRUE),
      (203, 5, 100, TRUE)
  `);
}

async function main() {
  try {
    await setup();

    const { db } = await import("@/db");
    const { deals, saleDeals } = await import("@/db/schema");
    const {
      canEditDeal,
      canEditSaleDeal,
      canViewDeal,
      canViewSaleDeal,
      dealsVisibleToSql,
      saleDealsVisibleToSql,
    } = await import("../visibility");

    type TestSession = Parameters<typeof canViewDeal>[0];

    async function visibleDealIds(session: TestSession) {
      const filter = dealsVisibleToSql(session);
      const rows = filter
        ? await db.select({ id: deals.id }).from(deals).where(filter)
        : await db.select({ id: deals.id }).from(deals);
      return rows.map((row) => row.id).sort((a, b) => a - b);
    }

    async function visibleSaleIds(session: TestSession) {
      const filter = saleDealsVisibleToSql(session);
      const rows = filter
        ? await db.select({ id: saleDeals.id }).from(saleDeals).where(filter)
        : await db.select({ id: saleDeals.id }).from(saleDeals);
      return rows.map((row) => row.id).sort((a, b) => a - b);
    }

    const adminSession: TestSession = { user: { agentId: 99, isAdmin: true, isActive: true } };
    assert.deepEqual(await visibleDealIds(adminSession), [101, 102, 103]);
    assert.deepEqual(await visibleSaleIds(adminSession), [201, 202, 203]);
    assert.equal(await canViewDeal(adminSession, 101), true);
    assert.equal(await canEditDeal(adminSession, 101), true);
    assert.equal(await canViewSaleDeal(adminSession, 201), true);
    assert.equal(await canEditSaleDeal(adminSession, 201), true);

    const participantSession: TestSession = { user: { agentId: 1, isAdmin: false, isActive: true } };
    assert.deepEqual(await visibleDealIds(participantSession), [101]);
    assert.deepEqual(await visibleSaleIds(participantSession), [201]);
    assert.equal(await canViewDeal(participantSession, 101), true);
    assert.equal(await canEditDeal(participantSession, 101), true);
    assert.equal(await canViewSaleDeal(participantSession, 201), true);
    assert.equal(await canEditSaleDeal(participantSession, 201), true);

    const leaderSession: TestSession = { user: { agentId: 4, isAdmin: false, isActive: true } };
    assert.deepEqual(await visibleDealIds(leaderSession), [102]);
    assert.deepEqual(await visibleSaleIds(leaderSession), [202]);
    assert.equal(await canViewDeal(leaderSession, 102), true);
    assert.equal(await canEditDeal(leaderSession, 102), false);
    assert.equal(await canViewSaleDeal(leaderSession, 202), true);
    assert.equal(await canEditSaleDeal(leaderSession, 202), false);

    const outsiderSession: TestSession = { user: { agentId: 2, isAdmin: false, isActive: true } };
    assert.deepEqual(await visibleDealIds(outsiderSession), []);
    assert.deepEqual(await visibleSaleIds(outsiderSession), []);
    assert.equal(await canViewDeal(outsiderSession, 102), false);
    assert.equal(await canEditDeal(outsiderSession, 102), false);
    assert.equal(await canViewSaleDeal(outsiderSession, 202), false);
    assert.equal(await canEditSaleDeal(outsiderSession, 202), false);

    const inactiveSession: TestSession = { user: { agentId: 5, isAdmin: false, isActive: false } };
    assert.deepEqual(await visibleDealIds(inactiveSession), []);
    assert.deepEqual(await visibleSaleIds(inactiveSession), []);
    assert.equal(await canViewDeal(inactiveSession, 103), false);
    assert.equal(await canEditDeal(inactiveSession, 103), false);
    assert.equal(await canViewSaleDeal(inactiveSession, 203), false);
    assert.equal(await canEditSaleDeal(inactiveSession, 203), false);

    const missingAgentSession: TestSession = { user: { agentId: null, isAdmin: false, isActive: true } };
    assert.deepEqual(await visibleDealIds(missingAgentSession), []);
    assert.deepEqual(await visibleSaleIds(missingAgentSession), []);
    assert.equal(await canViewDeal(missingAgentSession, 101), false);
    assert.equal(await canEditDeal(missingAgentSession, 101), false);
    assert.equal(await canViewSaleDeal(missingAgentSession, 201), false);
    assert.equal(await canEditSaleDeal(missingAgentSession, 201), false);

    console.log("visibility tests passed");
  } finally {
    const { closeDatabaseConnections } = await import("@/db");
    await closeDatabaseConnections();
    if (client) await client.end({ timeout: 2 }).catch(() => {});
    await adminClient.unsafe(`DROP DATABASE IF EXISTS ${dbName}`).catch(() => {});
    await adminClient.end({ timeout: 2 }).catch(() => {});
  }
}

main().catch((error) => {
  throw error;
});
